### ISSUE TITLE
PixiJS v6: Request to support generating a single TypeScript definition file

### ISSUE THREAD

**Issue by themoonrat** [pixijs/pixijs#7155] opened 2021-01-15 06:21 UTC
In PixiJS v5, a single definition file is created, that covers the entire library.
This is useful to be able to take and use for 'typings' in an IDE such as Visual Code / WebStorm, even when actually loading an application based on a pre-built browser build - either from bundling it locally, or loading pixi via a http script. A bit like DefinitelyTyped supplied. [Pixi playground](https://www.pixiplayground.com/) uses this for [live typings](https://www.pixiplayground.com/definitions/master/pixi.js.d.ts) in the browser, for example.

However, in PixiJS v6 typings are only provided on a per package basis, with the expectation that PixiJS is a devDependency on your project. Just like v6 does bundles to be used as both imported packages and purely in the browser, it'd be nice if there was an equivalent to both in the way the typings are generated, too.

**Comment by SukantPal** [comment] 2021-01-15 14:46
Not sure how to do this. A simple .dts concatenation won't work. Did you have any particular build implementation for this @themoonrat?

**Comment by andrewstart** [comment] 2021-01-15 17:01
You could try using something like
https://github.com/timocov/dts-bundle-generator, although as PixiJS is a
somewhat complicated project it may be too fiddly for the bundler.

**Comment by bigtimebuddy** [comment] 2021-01-15 17:27
I feel we are limited by what the tooling will support. I'm happy if someone wants to take a stab at this or try another approach, but a single typing file is probably a nice-to-have. What do other people think? Are other people expecting or clamoring for a single bundled type file like this?

I think the biggest constraint with the current set of tools (`@microsoft/api-extractor`) is that it doesn't support how we're dealing with globals. For plugins and class mixins, we use a `GlobalMixins` interface as a global type. This makes it easier to have plugins declare mixins. We tried a few things to rollup the mixins, but ended up having to create [this hack](https://github.com/pixijs/pixi.js/blob/dev/scripts/injectGlobalMixins.ts).

**Comment by ivanpopelyshev** [comment] 2021-01-20 09:30
We certainly need single-file `d.ts`

**Comment by mosike99** [comment] 2021-09-26 09:37
yes!   We certainly need single-file d.ts

**Comment by mosike99** [comment] 2021-09-26 09:44
Yes, we need a single .d.ts file.    How do I get this file : pixi.js.d.ts for 6.1.3   ?

**Comment by mosike99** [comment] 2021-09-27 03:29
So how do we get single-file: pixi.js.d.ts?      For our project, we must use single-file

**Comment by getepicerror** [comment] 2022-08-15 08:55
I would absolutely love to have this for our company. We're having problems migrating from 5 to 6 because of this exact issue.
We copy the needed libraries over from the npm dist folder, because we have a large amount of small(er) pixi projects. This is a must for the way we work with pixijs

**Comment by bigtimebuddy** [comment] 2022-08-15 11:05
To be clear @getepicerror are you looking for a single typing file for the browser bundle only (eg `PIXI` global)?

**Comment by getepicerror** [comment] 2022-08-15 11:13
@bigtimebuddy I think so. Our stack uses only howler, gsap and pixi.js .
Every project we create has a lib folder containing only the (distributed) js files that we copy once from NPM.
Along with that we have a definitions folder for development (some devs use VSCode, some IntelliJ) with the d.ts files that we usually copy from NPM too.
Up until PIXI 5 that has been working fine.
We do not modify pixi itself, and per project sometimes we decide to use PIXI filters.

**Comment by fy0** [comment] 2022-12-14 06:41
Still need this for v7.

**Comment by joebillman** [comment] 2023-08-02 23:17
I have started creating a single definition file. Basically, what I've been doing is copying the individual definition files into one file. It's not complete, but it's doable. Here is what I have so far:
[index.d.zip](https://github.com/pixijs/pixijs/files/12245413/index.d.zip)

**Comment by Laurens-Bamtang** [comment] 2024-01-19 21:59
This is a must for working with Visual Studio, for the ones that prefer that IDE

**Comment by timocov** [comment] 2024-01-21 02:08
Hi everyone, can someone validate if this bundle is valid and is what you'd like to have for this ticket? I was able to get it with https://github.com/timocov/dts-bundle-generator. If it is what you need, I can create a PR with proposed changes and you can decide if you want to merge it (it needs some tiny changes around `GlobalMixins` but nothing mind blowing, just moving stuff around 😂).

It was created for 5ae1d3b57e6e4a72f3b16f1836bd68eb37f75b9f commit in the dev branch.

[all-types.d.ts.zip](https://github.com/pixijs/pixijs/files/13999725/all-types.d.ts.zip)

**Comment by Laurens-Bamtang** [comment] 2024-01-22 20:32
Hi @timocov not luck here, 
There are a lot of errors if I replace your file with the one I'm using. I tried encasing all in a PIXI namespace and it lower the number of errors, but there are still plenty. But it seems a step in the right direction, I want to generate this myself for Pixi 6.x.
By the record I'm using VS Community 2022 in a repo folder like this: https://github.com/ex/js
This was the one for Pixi 5.x that I had previously: https://github.com/ex/js/blob/gh-pages/lib/pixi/pixi.js.d.ts

**Comment by timocov** [comment] 2024-01-22 21:23
@Laurens-Bamtang can you provide error list or how to reproduce the issue? It seems that the repo you mentioned is using v6 (or even v5 in your link), but what I've provided is for v7, I assume there might be some breaking changes between versions?

**Comment by timocov** [comment] 2024-01-24 21:35
@bamtang-dev this one should be better I think [pixijs.d.ts.zip](https://github.com/pixijs/pixijs/files/14043739/pixijs.d.ts.zip). It is generated for the same commit as the previous one. I noticed that some of classes aren't exported from PIXI (e.g. `Graphics` or `Container`) for some reason, it is not because the tool doesn't export them, but they aren't exported in https://github.com/pixijs/pixijs/blob/dev/packages/core/src/index.ts this file.

Unfortunately pixijs v6 is using on incompatible with dts-bundle-generator packages (e.g. typescript v4) so I couldn't create a bundle for v6.

**Comment by bamtang-dev** [comment] 2024-01-24 23:23
Yes this is better,
Manually adding the Graphics and Container definitions to the export here works:
```
declare namespace PIXI$1 {
	export { ALPHA_MODES, AbstractMultiResource, ..., Container, Graphics };
}
```
However these lines are still are a problem:
```
import { HslColor, HslaColor, HsvColor, HsvaColor, RgbColor, RgbaColor } from '@pixi/colord';
import { default as earcut$1 } from 'earcut';
import { default as EventEmitter } from 'eventemitter3';
```
Regarding Pixi 6, is very unfortune we can not use this with it, because we had definitions until 5.x and Pixi 6 broke that.

**Comment by timocov** [comment] 2024-01-25 17:54
> However these lines are still are a problem:

Sorry I'm not familiar with this library, does pixi mega-bundle includes all dependencies? If so, it can be easily fixed as well (these types will be inlined).

Conceptually, is it what you'd need? Is there a need for that from library maintainers? I can create a PR with proposed changes, but don't want to bother maintainers if it is not something that should be added.

**Comment by bigtimebuddy** [comment] 2024-01-25 18:30
I talked about this with the other maintainers earlier today. The consensus was if there's a simple solution to generate types for the browser bundles (i.e., creating ambient types for `PIXI` global), we should do it. But if it adds a lot of complexity, it's probably best iterated on as a community effort. We took this approach with things like HTMLText, developed as a plugin and then moved to the project once it was stable. Also, we would only consider this for upcoming v8, not prior major versions.

**Comment by bamtang-dev** [comment] 2024-01-25 19:00
> Sorry I'm not familiar with this library, does pixi mega-bundle includes all dependencies? If so, it can be easily fixed as well (these types will be inlined).

Yes, in-lining automatically them would be good, I was thinking about doing it manually...

> Conceptually, is it what you'd need? 
Yes, one single type definitions file to work with TypeScript without the need to download all the node modules.
As stated above there are other people also looking for this.

**Comment by timocov** [comment] 2024-02-03 20:41
I just created https://github.com/pixijs/pixijs/pull/10178 for this feature. Feel free to take a look and provide your feedback!

**Comment by timocov** [comment] 2024-04-10 00:02
Is this issue fixed by https://github.com/pixijs/pixijs/pull/10286 now?

**Closed** 2024-04-10 09:06 UTC
Labels: 🙏 Feature Request
