### ISSUE TITLE
Bug: GradientFill leaks memory

### ISSUE THREAD

**Issue by Liam-Hegarty** [pixijs/pixijs#11059] opened 2024-11-14 18:40 UTC
### Current Behavior

I am seeing memory leak whilst trying to dynamically GradientFill a graphics object (think of a skyline with a day/night cycle). I have made a quick example here:

https://www.pixiplayground.com/#/edit/y_qhrsKrn7b6lwHZ0_mX2

In my chrome developer tools [Version 131.0.6778.69 (Official Build) (arm64)] I see two things:

1. Memory usage steadily increasing
2. A growing list of detached canvas elements `<canvas width=256 height=256>`

I've attached a couple of things in case you can't replicate, a heap snapshot and an allocation timeline:

[Archive.zip](https://github.com/user-attachments/files/17756204/Archive.zip)

It's definitely the fill command on L31 that causes the leak, commenting it out stops the above issues.

Would be amazing if you could resolve this as it makes my game crash.

### Expected Behavior

No memory usage increase

### Steps to Reproduce

Continually fill a graphics element with a gradient fill. (eg: https://www.pixiplayground.com/#/edit/y_qhrsKrn7b6lwHZ0_mX2)

### Environment

- **`pixi.js` version**: *8.5.2*
- **Browser & Version**: *131.0.6778.69 (Official Build) (arm64)*
- **OS & Version**: *MacOS Sonoma 14.0*
- **Running Example**: *https://www.pixiplayground.com/#/edit/y_qhrsKrn7b6lwHZ0_mX2*

**Comment by bigtimebuddy** [comment] 2024-11-14 18:46
Duplicate of #10936?

**Comment by Liam-Hegarty** [comment] 2024-11-14 18:57
Absolutely, not sure how I missed that

**Closed** 2024-11-14 19:08 UTC
