### ISSUE TITLE
Container interactive Error

### ISSUE THREAD

**Issue by fengshaonianhuaming** [pixijs/pixijs#8976] opened 2022-12-15 02:41 UTC
when I set 
 let nextScreen = new PIXI.Container();
      nextScreen.sortableChildren = true;
      nextScreen.position.x = 0;
      nextScreen.position.y = 0;
      nextScreen.interactive = true;
then click
<img width="441" alt="image" src="https://user-images.githubusercontent.com/28429542/207759708-c570d6e4-2d57-4e41-9831-491d1c71ffbb.png">

**Comment by SuperSodaSea** [comment] 2022-12-15 03:33
Can you give some more detailed information, for example how do you add `nextScreen` to the stage?

**Comment by fengshaonianhuaming** [comment] 2022-12-15 06:07
this.pixiAPP.stage.addChild(nextScreen);

**Comment by fengshaonianhuaming** [comment] 2022-12-15 06:09
> Can you give some more detailed information, for example how do you add `nextScreen` to the stage?

this.pixiAPP.stage.addChild(nextScreen);

**Comment by fengshaonianhuaming** [comment] 2022-12-15 06:57
When I add sprite to the Container. and set interactive in sprite, and listen to the click event, this error occurs

**Comment by SuperSodaSea** [comment] 2022-12-16 20:51
<https://pixiplayground.com/#/edit/4dE4Az_D491Fuakc375XT>
I cannot reproduce the error. Could you provide an reproduction?

**Comment by Grimille** [comment] 2022-12-28 00:46
Hi folks,

I've ran into the same issue with a circle Graphics. Turning on interactive mode and mousemove event generate this error on console.

Here is my code : 
```javascript
    const circle = new Graphics();

    circle.beginFill(0x000000, 0.5);
    circle.drawCircle(450, 450, 200);
    circle.endFill();
    circle.blendMode = BLEND_MODES.ERASE;
    circle.interactive = true;

    overlayRect.addChild(circle);
    mainContainer.addChild(overlayRect);
    mainContainer.setTransform(window.innerWidth / 2 - canvas.value.width / 2, window.innerHeight / 2 - canvas.value.height / 2);
    app.value.stage.addChild(mainContainer);

    circle.on('mousemove', () => {
      console.log("Hello"); // doesn't even reach
      // circle.x = event.data.global.x;
      // circle.y = event.data.global.y;
    });
```
![Capture d’écran 2022-12-28 à 01 44 11](https://user-images.githubusercontent.com/5358149/209740469-23c8e9d1-85d3-4220-a4c5-877a63a81cef.png)

**Comment by Grimille** [comment] 2022-12-28 01:27
After further researches, it appears that the issue is caused by using a Vue.3 (Nuxt 3) ref to store the application instance. Everything is fine working without ref();

Hope it helps ! 🎈

**Comment by mariusk** [comment] 2023-02-23 22:11
FWIW, I'm getting the same error. I'm using PIXI with a React app, where I control the renderer and game loop myself. Everything works fine until I try to listen to click or similar. It even works, the handler is called, but the log is spammed with these errors. I don't have a minimum example, but will see if I can make one. But something is definitively very broken, and/or hard to get "right" (possibly related to PIXI making assumptions about external circumstances I suspect).

**Comment by mariusk** [comment] 2023-02-25 15:14
I managed to pin this issue down. Basically do not recreate the "stage" (the stuff you pass to the renderer) inside the gameloop. Weirdly enough, it works just fine, until I try to add interactivity to it. In retrospect it kind of makes sense, but it wasn't obvious immediately since the rest of the stuff worked seemed to work just fine. In my own engine I am managing dynamic "pixi components" and I just need to take a bit more care whenever those objects need to update/recreate their own display objects.

**Comment by TobiasWehrum** [comment] 2023-03-06 16:14
Yeah, this happened to me too when I recreated the stage after the event system's EventBoundary already self-attached itself to it.

My workaround for it is calling this after destroying/detaching the old stage:

```
app.renderer.events.rootBoundary = new EventBoundary(null);
```

**Comment by Zyie** [comment] 2023-03-24 20:00
Closing as workaround has been found: 

https://pixiplayground.com/#/edit/4dE4Az_D491Fuakc375XT

**Closed by Zyie** 2023-03-24 20:00 UTC
Labels: 👯‍♀️ Needs Reproduction

**Comment by TobiasWehrum** [comment] 2023-03-24 20:27
Isn't that something that should not *need* a workaround from Pixi users? I don't think the EventSystem should self-destruct because the stage is recreated.

**Comment by JoeriTheGreat** [comment] 2023-03-25 21:22
> Closing as workaround has been found:
> 
> https://pixiplayground.com/#/edit/4dE4Az_D491Fuakc375XT

Why do we need a workaround in pixi 7? pointermove events work fine in pixi 6. If we need to implement the move events differently please show how. But i don't like a workaround either..
