### ISSUE TITLE
Bug: too many active WebGL contexts on this page Safari

### ISSUE THREAD

**Issue by KostyaBekker** [pixijs/pixijs#10468] opened 2024-04-22 13:33 UTC
### Current Behavior

Destroy Application not working on safari and after 16 init new PIXI.Application() I get:
"There are too many active WebGL contexts on this page, the oldest context will be lost."
"WebGL: INVALID_OPERATION: loseContext: context already lost"

but on Chrome (123.0.6312.124) destroy work correct and I don't see that issue

### Expected Behavior

Destroy will work correct like in Chrome

### Steps to Reproduce

```
let playerCtl;

function init() {
  playerCtl = new PIXI.Application();
}

function destroy() {
  playerCtl.stop();
  playerCtl.destroy(true, { 'children': true });
  playerCtl = undefined;
}

function destroyPlayer() {
  setInterval(() => {
    init();
    setTimeout(() => {
      destroy();
    }, 100);
  }, 200);
 }
 
 destroyPlayer();
```
 
Example in jsfiddle https://jsfiddle.net/Bekker_Kostya/yurawg86/6/

Run this code in safari and open console.

### Environment

- **`pixi.js` version**: *e.g. 6.5.10*
- **Browser & Version**: *e.g. Safari 17.4.1*
- **OS & Version**: *e.g. macOS 14.4.1*
- **Running Example**: *e.g. https://jsfiddle.net/Bekker_Kostya/yurawg86/6/*

### Additional Information

I tryied use pixi 7 and 8 version but got the same issue.

**Comment by bigtimebuddy** [comment] 2024-04-22 15:30
Duplicate of #8814 #8215 #2596 see those issues for more context.

**Closed by bigtimebuddy** 2024-04-22 15:30 UTC
