### ISSUE TITLE
visual glitches in PIXI.TilingSprite from PIXI.Spritesheet 

### ISSUE THREAD

**Issue by TeeTeeHaa** [pixijs/pixijs#6735] opened 2020-07-01 20:13 UTC
### Expected Behavior

PIXI.TilingSprite looking correct no matter from which source it was created.

### Current Behavior

There are visual glitches (flickering) when moving a PIXI.TilingSprite that is created from a PIXI.Spritesheet that is created from an image for which mipmaps are generated which is the default for power-of-two sized images.

In the following screenshot the yellow lines in the middle (blue background) are looking wrong. In the provided "live" example those lines are flickering noticeably. The yellow lines on the left (red background) and the right (green background) are looking correct.
![screenshot](https://user-images.githubusercontent.com/739754/86286273-74858100-bbe6-11ea-86d0-eee43b26fdf3.png)

### Possible Solution

Workaround 1: Use a non-power-of-two sized image for the sprite sheet.

Workaround 2: Disable mipmaps completely before creating anything: ```PIXI.settings.MIPMAP_TEXTURES = PIXI.MIPMAP_MODES.OFF```

Both are only workarounds. I assume this has to be fixed within PIXI.TilingSprite.

### Steps to Reproduce

Just open the provided example in any browser.

### Environment

- **`pixi.js` version**: _5.3.0, 5.2.4_
- **Browser & Version**: _Firefox 77.0.1 on Windows 7 64 Bit, Ungoogled Chromium 80 on Windows 7 64 Bit, Chrome 84 on Android 9, Firefox Focus on Android 9_
- **OS & Version**: _Windows 7 64 Bit, Android 9_
- **Running Example** on GitHub: https://gist.github.com/TeeTeeHaa/01f2188eb358f913f9dee5f4bed8d3da
- **Running Example** on my private website: https://www.teeteehaa.de/pixijs/tilingsprite-from-spritesheet/

**Comment by ivanpopelyshev** [comment] 2020-07-02 10:59
> PIXI.TilingSprite looking correct no matter from which source it was created.

PixiJS does have all possible switches to make it work, the problem is that it cant actually detect what user wants for this texture.

Some info has to be passed to `texture.uvMatrix` or `tilingsprite.uvMatrix` instance -  clampOrigin has to be -0.5 or 0.5 depending on color of pixels are around your texture in spritesheet.

If you want to try to make heuristic that detects everything - go for it, I'll make cases that will break your implementation.

**Comment by TeeTeeHaa** [comment] 2020-07-02 18:49
> Some info has to be passed to `texture.uvMatrix` or `tilingsprite.uvMatrix` instance - clampOrigin has to be -0.5 or 0.5 depending on color of pixels are around your texture in spritesheet.

I tried out setting those attributes, with various different values, but without success. I would appreciate suggestions what I should do in my provided example to avoid the visual glitches (the flickering). I do not want to use any of the two workarounds I mentioned, because those have negative side effects.

**Comment by ivanpopelyshev** [comment] 2020-07-12 22:13
Of course I'll review your stuff in detail! When i have enough time.

All those isseus were addressed in https://github.com/pixijs/pixi.js/pulls?page=2&q=is%3Apr+tilingsprite and I doubt that we can do more than that, so it will be hard.

**Comment by TeeTeeHaa** [comment] 2020-10-12 20:11
Dear stale bot, no, this issue was not fixed yet, at least not in version 5.3.3 of pixi.js.

**Comment by TeeTeeHaa** [comment] 2021-03-12 23:11
Issue still exists in version 6.0.0 of pixi.js.

**Comment by TeeTeeHaa** [comment] 2021-06-13 20:20
Issue still exists in version 6.0.4 of pixi.js.
I do not want to start a fight with the stale bot. Next time it marks this issue as stale I will not comment on it even if the issue will not be fixed yet.

**Comment by ivanpopelyshev** [comment] 2021-06-13 20:59
> image being power-of-two + Spritesheet is just not possible to do. How do you actually want to do it?

**Comment by ivanpopelyshev** [comment] 2021-06-13 21:00
Actually its possible but only if client supports LOD's which is not always true, we need to add special case, e.t.c.

**Comment by ivanpopelyshev** [comment] 2021-06-13 21:16
Here's full current example, however there's somethign wrong with live reload https://codesandbox.io/s/pixi-tilingsprite-flickering-jbcjz

**Comment by ivanpopelyshev** [comment] 2021-06-13 21:19
Alternatively: find webgl renderer that does this thing fine, we can copy solution from it

**Comment by ivanpopelyshev** [comment] 2021-06-13 21:33
Basically, whats the problem: we had to revert https://github.com/pixijs/pixijs/pull/5211/files because such features aren't supported everywhere. If someone tells me which features are needed and what `texture2D` sampler we have to use, whether it needs webgl2, i can add an `if` in TilingSprite.

**Comment by TeeTeeHaa** [comment] 2021-06-15 20:17
> image being power-of-two(mipmaps) + Spritesheet is just not possible to do. How do you actually want to do it in webgl?

As far as I know Pixi.js automatically creates mipmaps for all quadratic images with power-of-two dimensions, for example 512 x 512 pixel. It does not do that for all other sizes, for example 511 x 511 pixel or 128 x 512 pixel.

As far as I know the documentation never mentions that sprite sheets cannot be based on textures which have mipmaps. Is there any reason that sprite sheets should *not* be based on textures which have mipmaps?

My knowledge about WebGL is limited. I do not understand why this bug is happening and I am not able to fix the bug. I only noticed there is something I would consider a "bug" (visually obvious flickering), I found out in which circumstances it happens (making a tiling sprite from an area inside a sprite sheet image which has mipmaps automatically generated) and I even found something I consider a "workaround" (disable automatic generation of mipmaps). I even learned that mipmaps are only automatically generated from images with power-of-two dimensions.

The fix you made in your live example (`tilingSpriteFromSpritesheet2.uvMatrix.clampMargin = 0.5;`) and the link you mentioned (https://github.com/pixijs/pixijs/pull/5211/files) unfortunately are beyond my little knowledge of WebGL. I am sorry that cannot be any further help here.

> Here's full current example, however there's somethign wrong with live reload https://codesandbox.io/s/pixi-tilingsprite-flickering-jbcjz

Despite your fix the output looks exactly the same as my own example (visible flickering).

If this issue cannot be fixed by code inside Pixi.js then close it as "unfixable". If this issue is to much work to fix and/or not a priority at the moment then close it as "won't fix". I'm ok with that. Thank you for spending time for this issue here.

**Comment by ivanpopelyshev** [comment] 2021-06-15 21:26
Thank you!

Well , actually, i have one more stupid idea - just add one more texture2D there or even use this for its own mips: https://forum.defold.com/t/sharp-sprite-rgss-for-defold/66840?u=agulev :)

Lets close it , but i will re-open as soon as i have time for quality optimization of this thing. Currently i work on serious quality improvement of shapes, and maybe its good idea to improve quality all over the renderer and make it big update :)

**Closed by ivanpopelyshev** 2021-06-15 21:26 UTC
