### ISSUE TITLE
Bug: pixi.min.js:457 Uncaught TypeError: Cannot read properties of undefined (reading 'width')

### ISSUE THREAD

**Issue by wz36125** [pixijs/pixijs#9105] opened 2023-01-24 14:29 UTC
### Current Behavior

When I write this code, the browser pops up this error。
`const app = new PIXI.Application();
    document.body.appendChild(app.view);`

### Expected Behavior

```js
const app = new PIXI.Application();
    document.body.appendChild(app.view);
    PIXI.Assets.load('img/spine/character/zny/01/spine.json').then(onAssetsLoaded);

    function onAssetsLoaded(spineAsset) {
      console.log(spineAsset);
      app.stage.interactive = true;

      // create a spine boy
      const spine = new PIXI.spine.Spine(spineAsset.spineData);

      // set the position
      spine.x = app.screen.width / 2;
      spine.y = app.screen.height;
      spine.scale.set(0.1);

      app.stage.addChild(spine);

      window.pp = spine;

      const allAnimations = spineAsset.spineData.animations;
      console.log(allAnimations);
      spine.state.addAnimation(0, "idle", true,0);

      // Press the screen to play a random animation
      app.stage.on('pointerdown', () => {
        spine.state.setAnimation(0, "click", false);
        spine.state.addAnimation(0, "idle", true,0);
      });
    }
```

### Steps to Reproduce

```js
const app = new PIXI.Application();
    document.body.appendChild(app.view);
    PIXI.Assets.load('img/spine/character/zny/01/spine.json').then(onAssetsLoaded);

    function onAssetsLoaded(spineAsset) {
      console.log(spineAsset);
      app.stage.interactive = true;

      // create a spine boy
      const spine = new PIXI.spine.Spine(spineAsset.spineData);

      // set the position
      spine.x = app.screen.width / 2;
      spine.y = app.screen.height;
      spine.scale.set(0.1);

      app.stage.addChild(spine);

      window.pp = spine;

      const allAnimations = spineAsset.spineData.animations;
      console.log(allAnimations);
      spine.state.addAnimation(0, "idle", true,0);

      // Press the screen to play a random animation
      app.stage.on('pointerdown', () => {
        spine.state.setAnimation(0, "click", false);
        spine.state.addAnimation(0, "idle", true,0);
      });
    }
```

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by SuperSodaSea** [comment] 2023-01-24 15:18
Which version of `pixi.js` and `pixi-spine` are you using?

**Comment by wz36125** [comment] 2023-01-25 01:43
> Which version of `pixi.js` and `pixi-spine` are you using?

Yes, but that's not the point. Even if I write the following code, it still reports this error.
`function loadScript(path,onload,onerror) {
        var script = document.createElement('script');
        script.onload = function () {
          console.log(path + " OK");
          if (onload) onload();
        };
        script.onerror = function () {
          this.remove();
          console.error(this.src + 'not found');
          if (onerror) onerror();
        };
        script.src = path;
        document.head.appendChild(script);
      }

      loadScript(`${S.path}/pixi.min.js`,function () {
        const app = new PIXI.Application();
      });`

error message:
`pixi.min.js:457 Uncaught TypeError: Cannot read properties of undefined (reading 'width')
    at Gr.init (pixi.min.js:457)
    at pixi.min.js:457
    at Array.forEach (<anonymous>)
    at Yr.emitWithCustomOptions (pixi.min.js:457)
    at Nr.run (pixi.min.js:457)
    at new Yr (pixi.min.js:494)
    at Ko (pixi.min.js:457)
    at new sn (pixi.min.js:834)`

**Comment by wz36125** [comment] 2023-01-25 01:51
download link:
https://pixijs.download/v7.1.1/pixi.min.js

**Comment by bigtimebuddy** [comment] 2023-01-25 04:01
I cannot reproduce: https://jsfiddle.net/bigtimebuddy/pb4omwaf/

**Comment by wz36125** [comment] 2023-01-25 04:16
> I cannot reproduce: https://jsfiddle.net/bigtimebuddy/pb4omwaf/

Yes, but very strange. This code works without any errors in pixi v6.5.8. The operating environment is in **### electron**.

**Comment by bigtimebuddy** [comment] 2023-01-25 04:54
Could you please provide a minimal reproduction of the issue?

**Comment by wz36125** [comment] 2023-01-25 05:35
> Could you please provide a minimal reproduction of the issue?

You have to trust me, I'm not lying to you. That's all the code.
After successfully loading pixi.min.js v7.1.1, the Window layer has the global object of PIXI. However, an error is reported when running to "const app = new PIXI.Application();".
The same code works without any problem under pixi.js v6.5.8.

because i'm learning pixi v7.
`function loadScript(path,onload,onerror) {
        var script = document.createElement('script');
        script.onload = function () {
          console.log(path + " OK");
          if (onload) onload();
        };
        script.onerror = function () {
          this.remove();
          console.error(this.src + 'not found');
          if (onerror) onerror();
        };
        script.src = path;
        document.head.appendChild(script);
      }
      loadScript("https://pixijs.download/v7.1.1/pixi.min.js",function () {
        const app = new PIXI.Application();
      })`

**Comment by wz36125** [comment] 2023-01-25 08:23
If this problem cannot be solved, I will continue to use 
> pixi v6.5.8

**Comment by SuperSodaSea** [comment] 2023-01-25 08:58
I tried your code in electron and nothing goes wrong. What is your electron's version & setting?

**Comment by wz36125** [comment] 2023-01-25 09:18
> I tried your code in electron and nothing goes wrong. What is your electron's version & setting?

ares: "1.17.2"
brotli: "1.0.9"
chrome: "96.0.4664.55"
electron: "16.0.4"
icu: "69.1"
llhttp: "6.0.2"
modules: "99"
napi: "8"
nghttp2: "1.42.0"
node: "16.9.1"
openssl: "1.1.1"
unicode: "13.0"
uv: "1.42.0"
v8: "9.6.180.12-electron.0"
zlib: "1.2.11"

**Comment by SuperSodaSea** [comment] 2023-01-25 09:19
BTW the stacktrace goes here:

<https://github.com/pixijs/pixijs/blob/99b26d1d5a18760019b034c69c5979ca5e6c536b/packages/core/src/view/ViewSystem.ts#L84>
<https://github.com/pixijs/pixijs/blob/99b26d1d5a18760019b034c69c5979ca5e6c536b/packages/core/src/system/SystemManager.ts#L136>
<https://github.com/pixijs/pixijs/blob/99b26d1d5a18760019b034c69c5979ca5e6c536b/packages/core/src/startup/StartupSystem.ts#L50>
<https://github.com/pixijs/pixijs/blob/99b26d1d5a18760019b034c69c5979ca5e6c536b/packages/core/src/Renderer.ts#L408>

**Comment by SuperSodaSea** [comment] 2023-01-25 09:24
Tried electron@16.0.4 and still nothing wrong. Would you like to create a small repository on GitHub that can reproduce your issue?

**Comment by wz36125** [comment] 2023-01-25 09:41
> Tried electron@16.0.4 and still nothing wrong. Would you like to create a small repository on GitHub that can reproduce your issue?

I don't have an uncompiled version.
This is a game developed by JavaScript and electron, it is a windows platform, the file size is 80MB.
download link:
[file](https://wz36125.github.io/assets/game/v1.36.exe)

**Comment by wz36125** [comment] 2023-01-25 10:39
> It looks like the file you gave has nothing to do with pixi.js.

No, this program allows users to write extensions. I successfully played the skeleton file using pixi v6.5.8. If you download and install this file, you can press ctrl + J on the keyboard to open the developer tool after running the program. Just like using the Chrome browser F12 developer tools

**Comment by SuperSodaSea** [comment] 2023-01-25 10:43
> > It looks like the file you gave has nothing to do with pixi.js.
> 
> No, this program allows users to write extensions. I successfully played the skeleton file using pixi v6.5.8. If you download and install this file, you can press ctrl + J on the keyboard to open the developer tool after running the program. Just like using the Chrome browser F12 developer tools

Yeah, this do reproduce this issue. I'm looking into it.

**Comment by SuperSodaSea** [comment] 2023-01-25 11:06
This problem is caused by a bad polyfill in the application you gave:

```js
Array.prototype.find = function(item) {
    return this.indexOf(item);
};
```

Standard [`Array.prototype.find()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) should accept function instead of item. You can write another polyfill to override this behavior, for example:

```js
Array.prototype.find=function(item){
    if(item instanceof Function) {
        for(let i = 0; i < this.length; ++i)
            if(item(this[i], i, this)) return this[i];
        return undefined;
    }
    // Your application may still rely on the bad polyfill
    return this.indexOf(item);
};
```

**Comment by wz36125** [comment] 2023-01-25 11:10
> This problem is caused by a bad polyfill in the application you gave:
> 
> ```js
> Array.prototype.find = function(item) {
>     return this.indexOf(item);
> };
> ```
> 
> Standard [`Array.prototype.find()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) should accept function instead of item. You can write another polyfill to override this behavior, for example:
> 
> ```js
> Array.prototype.find = function(item) {
>     if(item instanceof Function) {
>         for(let i = 0; i < this.length; ++i)
>             if(item(this[i], i, this)) return this[i];
>         return undefined;
>     }
>     // Your application may still rely on the bad polyfill
>     return this.indexOf(item);
> };
> ```
> 
> Run the above code before you load pixi.js.

thank you very much！！😆

**Comment by SuperSodaSea** [comment] 2023-01-25 11:28
I'm going to close this issue. Feel free to reopen it if you still have problems.

**Closed by SuperSodaSea** 2023-01-25 11:28 UTC
Labels: 👍 Not A Bug

**Comment by aidv** [comment] 2024-01-05 13:53
I'm experiencing the same issue.

I'm on electron@21.4.2 and the RC version of Pixi
