### ISSUE TITLE
Creating a new BitmapText object fails after calling destroy on a previous one when using a font that is split up into multiple pages.

### ISSUE THREAD

**Issue by p-gerasimov** [pixijs/pixijs#8712] opened 2022-10-10 10:15 UTC
### Expected Behavior
To create `BitmapText` objects without any errors.
### Current Behavior
Creating a new `BitmapText` after destroying a previous one results in a `Cannot read properties of null (reading 'alphaMode')` error.
### Steps to Reproduce
Like I did [_here_](https://codesandbox.io/s/pixi-bitmap-bug-knbhby?file=/src/index.js).
Create a `BitmapText` object with an initial value of characters that are from 2 different pages and add it to the stage. 
Wait for at least one frame and change the text to a character that is in only one of the pages.
Wait for another frame and destroy the `BitmapText` object.
After that, try creating a new `BitmapText` with any of the previous characters used and observe the error.
### Environment

- **`pixi.js` version**: 6.5.5
- **Browser & Version**: Chrome 105, Firefox 105, Brave 1.144
- **OS & Version**: Windows 10
- **Running Example**: [_example_](https://codesandbox.io/s/pixi-bitmap-bug-knbhby?file=/src/index.js)

**Comment by bigtimebuddy** [comment] 2022-10-10 14:54
Thanks for the reproduction. This seems like a bug. 

Here's the full stack.

```
mesh.mjs:276 Uncaught TypeError: Cannot read properties of null (reading 'alphaMode')
    at set texture [as texture] (mesh.mjs:276:47)
    at set texture [as texture] (mesh.mjs:110:24)
    at _BitmapText.updateText (text-bitmap.mjs:715:34)
    at _BitmapText.validate (text-bitmap.mjs:848:12)
    at _BitmapText.updateTransform (text-bitmap.mjs:820:10)
    at Container.updateTransform (display.mjs:699:15)
    at ObjectRendererSystem.render (core.mjs:6867:21)
    at _Renderer.render (core.mjs:6125:25)
    at _Application.render (app.mjs:23:19)
    at TickerListener.emit (ticker.mjs:37:17)
```

**Comment by SuperSodaSea** [comment] 2022-10-10 15:23
https://github.com/pixijs/pixijs/blob/v6.5.5/packages/text-bitmap/src/BitmapText.ts#L372-L384

It seems that the `Texture` used in the `pageMeshDataPool` is destroyed in previous `BitmapText.destroy()`, causing the error.
Here is what happened:
- When the `"12"` is rendered, two `PageMeshData` are created.
- When the `"12"` is changed to `"1"`, the two `PageMeshData` are pushed into the `pageMeshDataPool`, and one of the `PageMeshData` is poped for use, left another `PageMeshData` in the pool.
- The `BitmapText.destroy()` is called, the textures used in the `PageMeshData` is also `destroy()`ed, but one of the  `PageMeshData` is still in the pool.
- When the new `BitmapText` is rendered, the broken `PageMeshData` is taken from the pool, causing the error.

**Comment by bigtimebuddy** [comment] 2022-10-10 15:27
Assigning to `Texture.EMPTY` to used pool textures on destroy fixed this.

**Closed** 2022-10-11 14:01 UTC
Labels: 🕷 Bug

**Comment by tylerfurtwangler** [comment] 2022-10-14 01:23
@bigtimebuddy I think this can still happen when using texture based bitmaps and using children destroy options.  See fiddle here that does not fail in v6.5.2 and does fail in v6.5.6:  https://codesandbox.io/s/pixi-bitmap-bug-2-hl9wry?file=/src/index.js

**Comment by SuperSodaSea** [comment] 2022-10-14 01:56
> @bigtimebuddy I think this can still happen when using texture based bitmaps and using children destroy options. See fiddle here that does not fail in v6.5.2 and does fail in v6.5.6: https://codesandbox.io/s/pixi-bitmap-bug-2-hl9wry?file=/src/index.js

@tylerfurtwangler You `text1.destroy()` twice. Should be `text2.destroy()`.

**Comment by tylerfurtwangler** [comment] 2022-10-14 02:10
Apologies I can’t seem to get the saved version to share 😠 

I’m any case, should reproduce when updating it to destroy text1 then text2 (rather than text1 twice) and using `{ children: true }` option to both which was my intention.

I’ll see if I can share a link to the right code snippet once I am back at computer.

**Comment by SuperSodaSea** [comment] 2022-10-14 02:51
```js
const text1 = new BitmapText("1", fontSettings);
stage.addChild(text1);
await wait(100);
text1.destroy({ children: true });

const text2 = new BitmapText("1", fontSettings);
stage.addChild(text2);
```

This is enough to reproduced the problem. Seemed to be caused by #8719, the mesh is pushed into pool and then destroyed. I'll make a PR to fix it later.
@tylerfurtwangler Since this is different from this issue, would you like to create a new issue for this?

**Comment by tylerfurtwangler** [comment] 2022-10-14 03:39
Thanks @SuperSodaSea I have opened https://github.com/pixijs/pixijs/issues/8732, feel free to update it as needed. I provided links for reproducing in v6.5.6 and showing that it does not reproduce in v6.5.2 but it sounds like you already have a clear idea of the cause.
