### ISSUE TITLE
Bug: Text shadow is awkward on IOS

### ISSUE THREAD

**Issue by talhaozdemir** [pixijs/pixijs#9370] opened 2023-04-12 11:52 UTC
### Current Behavior

![Untitled](https://user-images.githubusercontent.com/37840852/231448197-f8ae336b-4ba4-4280-9961-059aa8523b80.jpg)

Text shadow is bad on IOS devices (the bottom frame)

### Expected Behavior

it should be like the first frame in the image

### Steps to Reproduce

just add shadow to any text

### Environment

- **`pixi.js` version**: *6.5.9*
- **OS & Version**: *iPhone 7 IOS: 15.6.1*

**Comment by bigtimebuddy** [comment] 2023-04-12 16:18
Duplicate of #7502

**Closed by bigtimebuddy** 2023-04-12 16:18 UTC
