### ISSUE TITLE
Error v6.5.1: Extension type renderer-webgl-plugin already has a handler 

### ISSUE THREAD

**Issue by Makio64** [pixijs/pixijs#8530] opened 2022-07-25 04:25 UTC
After updated pixi from 6.4.x to the new 6.5.1 I got this error `Extension type renderer-webgl-plugin already has a handler `
I double checked i have only one Application started.

ps: To update: i did the yarn remove pixi.js / yarn add pixi.js

- **`pixi.js` version**: 6.5.1

**Comment by bigtimebuddy** [comment] 2022-07-25 09:18
Can you provide a reproduction?

**Comment by bigtimebuddy** [comment] 2022-07-25 10:30
I have a somewhat vanilla webpack/pixijs project [here](https://github.com/bigtimebuddy/pixi-sound-webpack-example) and cannot reproduce this error with 6.5.1.

**Comment by EneaEntertainment** [comment] 2022-07-26 13:54
I was having same issue, but as @bigtimebuddy suggested me - uninstalling and also deleting lock file before new install helped

**Comment by bigtimebuddy** [comment] 2022-07-26 14:29
Also, please read this: https://github.com/pixijs/pixijs/wiki/Upgrading-PixiJS

**Comment by Makio64** [comment] 2022-08-09 13:01
@bigtimebuddy thanks it works when I delete the yarn.lock, but pixi is the only repo i'm using who needs this kind of extra steps to update. I guess it should be a way to avoid that.

**Comment by Zyie** [comment] 2023-03-24 20:14
Closing as this was resolved by delete the lock file. See the [Upgrading Pixi](https://github.com/pixijs/pixijs/wiki/Upgrading-PixiJS) wiki for more info

**Closed by Zyie** 2023-03-24 20:14 UTC
Labels: 👯‍♀️ Needs Reproduction

**Comment by HiggsWRX** [comment] 2023-03-29 12:29
This solution does not work for me.

I have followed every suggestion. Properly uninstall, remove lock file, etc.
On a clean install I still get this error when trying to load pixi
