### ISSUE TITLE
Can't import the named export 'ALPHA_MODES' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by tungleanh92** [pixijs/pixijs#8554] opened 2022-08-06 08:05 UTC
This is my error:
./node_modules/@pixi/core/dist/esm/core.mjs
Can't import the named export 'ALPHA_MODES' from non EcmaScript module (only default export is available)

These are my dependencies:
"@pixi/core": "^6.5.1",
    "@pixi/display": "^6.5.1",
    "@pixi/sprite": "^6.5.1",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "antd": "^4.21.6",
    "axios": "^0.27.2",
    "ethers": "^5.6.7",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^5.3.3",
    "react-scripts": "4.0.3",
    "react-tooltip": "^4.2.21",
    "socket.io-client": "^4.1.2",
    "styled-components": "^5.3.0",
    "typescript": "^4.1.2",
    "web-vitals": "^1.0.1",
    "webpack": "^4.44.2"
   
I tried some solution on the internet using webpack but it did not work?
Can you help me with this? Many thanks

**Comment by bigtimebuddy** [comment] 2022-08-06 10:23
ALPHA_MODES should be imported from `@pixi/constants` not from `@pixi/core`.

If you are going to use individual packages (e.g., `@pixi/core`) please check out [this tool](https://pixijs.io/customize/) for customizing PixiJS. There's some boilerplate-code that's currently needed to link bits together.

**Comment by talhaozdemir** [comment] 2022-08-06 12:59
Adding
            {
                test: /\.mjs$/,
                include: /node_modules/,
                type: 'javascript/auto'
            }

in the webpack config is solved the issue for me.

**Comment by bigtimebuddy** [comment] 2022-08-10 15:06
Closing this as it seems answered. Happy to re-open, if not.

**Closed by bigtimebuddy** 2022-08-10 15:06 UTC

**Comment by clonecodes** [comment] 2022-08-18 13:21
@talhaozdemir could you give a bit more info, like add exactly where in webpack config, or provide an example?
Much appreciated

**Comment by talhaozdemir** [comment] 2022-08-19 15:58
In the webpack configuration file, it is something like that: 

`module.exports = {
    module: {
        rules: [
            {
                test: /\.mjs$/,
                include: /node_modules/,
                type: 'javascript/auto'
            }
        ]
    }
}`

**Comment by Thel27** [comment] 2022-08-24 14:50
Same problem and I'm not using webpack

**Comment by bigtimebuddy** [comment] 2022-08-24 15:05
Can someone please provide a reproduction?

Upgrading to v5 of Webpack should also help, if folks are able to upgrade that tool.

**Comment by jingyuLin1999** [comment] 2022-09-06 09:40
I have the same issue. 
![image](https://user-images.githubusercontent.com/30433062/188601794-ade07efd-8cd7-4b99-b662-925002e8f800.png)
environment:
    "vue": "^2.6.11",
    "pixi.js": "^6.5.2",
when I install pixi.js@5, it work.

**Comment by jettoki** [comment] 2022-09-21 20:54
For those of you using **Laravel Mix**, you need to add this to your webpack.mix.js

```
mix.webpackConfig({
    module: {
        rules: [
            {
                test: /\.mjs$/,
                include: /node_modules/,
                type: 'javascript/auto'
            }
        ]
    }
});
```

Otherwise, you get a cascade of errors. ("only default export is available"). Thanks to @talhaozdemir for the solution.

It seems very strange that Pixi.js requires this, though? I've never had to extend my webpack config to accommodate a module before. What's causing this exactly?

**Comment by bigtimebuddy** [comment] 2022-09-21 21:08
Support for *.mjs is on by default in Webpack 5+. Earlier versions you have to enabled it. We change the extension on our ESM builds from .js to .mjs to support Node.js rendering.

**Comment by paullacour** [comment] 2022-09-30 13:12
In Nuxt just add this to your build settings in nuxt.config.js and it solves the problem:
`  build: {
    extend(config) {
      config.module.rules.push({
        test: /\.mjs$/,
        include: /node_modules/,
        type: 'javascript/auto',
      })
    },
  },`

**Comment by kisa777zaika** [comment] 2022-11-03 10:56
> In Nuxt just add this to your build settings in nuxt.config.js and it solves the problem:
> 
> ```
> build: {
>     extend(config) {
>       config.module.rules.push({
>         test: /\.mjs$/,
>         include: /node_modules/,
>         type: 'javascript/auto',
>       })
>     },
>   },
> ```

Nothing changed in Nuxt :(

**Comment by paullacour** [comment] 2022-11-03 11:02
@kisa777zaika check your version of Pixi in package.json. I couldn't get the last version to run in Nuxt at all, but v5 did the trick: `"pixi.js": "^5.0.0",`

**Comment by bigtimebuddy** [comment] 2022-11-03 12:27
Webpack 4 (and tools that use Webpack 4) seems to have issues with mjs extensions for module JS. This was changed in PixiJS 6.5+. If you need a workaround that is > 5.0.0, consider 6.4.

**Comment by jasonsturges** [comment] 2022-12-02 20:30
Also seeing this using Vite for building packages.

**Comment by bigtimebuddy** [comment] 2022-12-02 21:29
@jasonsturges I created a vanilla JS vite w/ pixi here: https://github.com/bigtimebuddy/pixi-vite-vanilla-example

I was not able to reproduce. Please file a new issue.
