### ISSUE TITLE
Bug: [v8] Background alpha doesn't have an effect on WebGPU

### ISSUE THREAD

**Issue by levi** [pixijs/pixijs#9816] opened 2023-10-31 13:32 UTC
### Current Behavior

Setting the background alpha option when initializing the app doesn't change the alpha of the background.

### Expected Behavior

Alpha should blend or completely remove the background based on value.

### Steps to Reproduce

const app = new Application()
await app.init({
backgroundAlpha: 0
})

### Environment

- **`pixi.js` version**:  v8 Beta 7

**Comment by bigtimebuddy** [comment] 2023-10-31 15:34
Duplicate of #9799

**Closed** 2023-11-27 09:47 UTC
Labels: v8
