### ISSUE TITLE
Error: "exports is not defined"

### ISSUE THREAD

**Issue by BlockI0tChain** [pixijs/pixijs#8673] opened 2022-09-27 08:01 UTC
### Since last week  i believe the module is not building and showing the following error:
with: v6.5.4
    Uncaught ReferenceError: exports is not defined
        at pixi.js:10:23
    (anonymous) @ pixi.js:10

with: v7.0.0-alpha.3: 
console shows no error, but Pixi isn't building/working. 

I believe the new version (v6.5.4) is breaking the build due to some some dependency issue.
The alpha version isn't working either, no ideea why since i get no error logged in the console. 
Any thoughts?
 

     

### Steps to Reproduce
import * as PIXI from 'http://127.0.0.1:8080/js/pixi.js' ;

### Environment

- **`pixi.js` version**: v6.5.4  and v7.0.0-alpha.3
- **Browser & Version**: version 105.0.5195.125 (Official Build) (arm64) 
- **OS & Version**: MacOS 12.6
- **Running Example**: -

**Comment by bigtimebuddy** [comment] 2022-10-03 14:19
Can you please show a complete example? How are you building/running this?

**Comment by BlockI0tChain** [comment] 2022-10-03 16:48
Ahmm it's actually simple.   I'm generating some orbs in background on a html page with PIXI.
I noticed the error after the v6.5.4. I was using PIXI from the skypack.dev CDN source.
I'm calling the js code from an external script file .

`<script type="module" src="js/somescript.js"></script>`

In the script the Pixi  and some other modules  must be imported, and are being built at this step.

``` 
import * as PIXI from "https://cdn.skypack.dev/pixi.js";
import { KawaseBlurFilter } from "https://cdn.skypack.dev/@pixi/filter-kawase-blur";
... 
import SimplexNoise from "https://cdn.skypack.dev/simplex-noise";
import { createNoise2D } from "https://cdn.skypack.dev/simplex-noise"; */
``` 

Then 

``` 
// PIXI.Graphics is initialised to draw some 2d circles to the canvas
     this.graphics = new PIXI.Graphics();
     this.graphics.alpha = 0.105;
``` 
Anyways whatever pixi must do afterwards isn't relevant here because the script breaks during the import ` import * as PIXI from "https://cdn.skypack.dev/pixi.js";` 
Nothing else gets executed past it that's why i haven't included details of the script.

 Hope it makes sense.

**Comment by bigtimebuddy** [comment] 2022-10-03 17:27
This is a duplicate of https://github.com/pixijs/pixijs/issues/8682

v6.5.4 is broken on skypack for some unknown reason. v6.5.5 fixed the issue.

**Comment by BlockI0tChain** [comment] 2022-10-04 08:18
Indeed works in v6.5.5.  big time thanks buddy! No idee what happened because I've checked both versions and I see now difference.

**Closed** 2022-10-04 09:32 UTC
Labels: 👯‍♀️ Needs Reproduction
