### ISSUE TITLE
Access denied to script URL's from pixijs.io/customize/

### ISSUE THREAD

**Issue by hilmia** [pixijs/pixijs#8857] opened 2022-11-17 11:40 UTC
All the custom scripts that I need from pixijs.io/customize/ throw a 403 Access Denied since a few days, these were working last time I checked last week.

```
<script src="https://pixijs.download/release/packages/canvas-display.min.js"></script>
<script src="https://pixijs.download/release/packages/canvas-renderer.min.js"></script>
<script src="https://pixijs.download/release/packages/canvas-graphics.min.js"></script>
```

Please advice if this will be solved as now the PIXI scripts in my app aren't working

**Comment by SuperSodaSea** [comment] 2022-11-17 13:14
PixiJS v7 no longer provide seperate `.js` for most of the packages. You can:
- Replace `release` with `v6.x` in the URL to use PixiJS v6
- Use `<script src="https://pixijs.download/release/pixi-legacy.min.js"></script>` which contains almost every packages you need
- Use bundler, for example `import * from '@pixi/canvas-display'`

**Comment by bigtimebuddy** [comment] 2022-11-17 13:43
The only other thing I would add to this, is we decided to remove the individual browser builds for each package because many people were not using this and it was adding complexity/time to our build process. Using individual packages is more of an advanced workflow to optimize around file-size. If you need to use individual packages, please consider bundling them together yourself. We'll be updating the customize tool soon to reflect these changes.

**Comment by hilmia** [comment] 2022-11-17 14:01
Ok thank you, using `<script src="https://pixijs.download/release/pixi-legacy.min.js"></script>` solved the problem.

Could you perhaps announce / write about a change like this next time

**Comment by Zyie** [comment] 2023-03-24 20:02
Closing as this is not a bug

See [this](https://github.com/pixijs/pixijs/issues/8857#issuecomment-1318659730) comment for more info

**Closed by Zyie** 2023-03-24 20:02 UTC
Labels: 👍 Not A Bug
