### ISSUE TITLE
Bug: Fill hex for black produces unpredictable results

### ISSUE THREAD

**Issue by iDVB** [pixijs/pixijs#10369] opened 2024-03-22 16:48 UTC
### Current Behavior

Simply setting a graphics fill color of black doesn't work and has unpredictable results.
In the Simple PixiJS playground demo, changing the fill of one of the graphics to black seems to be ignored and the previous color is used.

In my own examples using 0x000000 will net to "white" while 0x000001 will be black, but assuming its actually 0x000001 black and not the actual 0x000000 black.

    const graphics = new PIXI.Graphics().rect(0, 0, 300, 300).fill(0x000000);
    app.stage.addChild(graphics);

### Expected Behavior

Setting a fill color of 0x000000 should be black

### Steps to Reproduce

https://codesandbox.io/p/sandbox/frosty-star-forked-xhfcv7

### Environment

- **`pixi.js` version**: *v8.0.3*
- **Browser & Version**: *Version 122.0.6261.129*
- **OS & Version**: *13.6.4 (22G513)*
- **Running Example**: *https://codesandbox.io/p/sandbox/frosty-star-forked-xhfcv7*

**Comment by bigtimebuddy** [comment] 2024-03-22 19:42
Duplicate of #10363

**Closed** 2024-03-22 19:42 UTC
