### ISSUE TITLE
Bug: Container.destroy() does not work when Container is an instance of ParticleContainer

### ISSUE THREAD

**Issue by RootInit** [pixijs/pixijs#11010] opened 2024-10-22 22:21 UTC
### Current Behavior

When attempting to clear a container by iterating through it and destroying the child elements I discovered a bug where ParticleContainers cannot be destroyed using Container.destroy()
Gives error:
```
Uncaught (in promise) Error: ParticleContainer.removeChildren() is not available. Please use ParticleContainer.removeParticles()
    at _ParticleContainer.removeChildren (ParticleContainer.ts:387:15)
    at _ParticleContainer.destroy (Container.ts:1346:34)
    at _ParticleContainer.destroy (ViewContainer.ts:97:15)
    at _ParticleContainer.destroy (ParticleContainer.ts:287:15)
    at demo.js:23:27
```

### Expected Behavior

The ParticleContainer should be destroyed like a normal Container

### Steps to Reproduce

```js 
(async () => {
    const app = new PIXI.Application();
    await app.init({
        width: window.innerWidth,
        height: window.innerHeight,
        backgroundColor: 0x2c3e50,
        resizeTo: window,
        autoDensity: true,
        resolution: window.devicePixelRatio
    })

    document.body.appendChild(app.canvas);

    const container = new PIXI.Container()
    container.addChild(new PIXI.ParticleContainer())
    container.children[0].destroy()
})();
```

### Environment

Provided code works in the playground, presumably latest version.

### Possible Solution

I believe this should be a simple fix just by adding a ParticleContainer.removeChildren() function that just calls removeParticles()

**Comment by bigtimebuddy** [comment] 2024-10-22 22:36
This is a duplicate of #10999 and has been addressed in #11006

**Closed by bigtimebuddy** 2024-10-22 22:36 UTC
