### ISSUE TITLE
'Self is not defined', SSR (Sveltekit)

### ISSUE THREAD

**Issue by einarpersson** [pixijs/pixijs#7703] opened 2021-08-15 11:23 UTC
I am using pixi.js in Sveltekit. Sveltekit is a flexible framework where you can do SSR, SSG, and SPAs (and mix).

Since pixi.js is a browser only library it gets into trouble with SSR. 

What surprises me is that merely importing the module will crash it, even if nothing is instantiated. This forces you to use [dynamic imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports). It is an extra step which creates problems when using Typescript since you can't import types without crashing everything (or at least I haven't figured out how).

Is this something that is being worked on? Or is this fundamentally not possible to solve?

### Related? 
[Totally random "ReferenceError: self is not defined" in "isMobile.ts" during tests](https://github.com/pixijs/pixijs/issues/7657)
["window is undefined" in nextjs](https://github.com/pixijs/pixijs/issues/6990)

I created a new ticket since I'm not sure how/if these relate, and I wanted to contribute with a minimal reproducible example.

### Expected Behavior

I expect it to be possible to import the module, but not being able to instantiate classes that depend on browser context.

### Current Behavior

Just the act of importing pixi.js crashes in a non-browser environment, whether you do something with it or not.

### Possible Solution

Don't know really. 

Maybe there are workarounds. I'm new to pixi.js.

### Steps to Reproduce

````
npm init svelte@next my-app
cd my-app
nvm use 16
npm i
npm i pixi.js
````
and then import pixi.js in `index.svelte`

````
<script>
    import { onMount } from 'svelte'
    
    // 1. **********************
    // This does not work.
    // Even though the Application never is being instansiated. 
    // Just importing anything from 'pixi.js' will crash the app.
    // import { Application } from 'pixi.js'

    onMount(async () => {
        // 2. ****************
        // This do work, but creates unnecessary hassle, 
        // especially when you start using Typescript and want to be able to import types
        const { Application } = (await import('pixi.js'))
    })
</script>

<h1>Hello world</h1>

````

### Environment

- **`pixi.js` version**: 6.1.2
- **Browser & Version**: NA
- **OS & Version**: Ubuntu 18.04
- **Running Example**:

**Comment by miltoncandelero** [comment] 2021-08-15 13:09
> can't import types without crashing everything (or at least I haven't figured out how).

Not sure if you tried but... 
`import type { Sprite } from "pixi.js"`

Import type should only be used to enforce types and not run code

**Comment by andrewstart** [comment] 2021-08-15 13:12
Importing a type with no code to back it up is done as `import type
{Application} from 'pixi.js'`. You would probably want to do `import type *
as PixiLib from 'pixi.js'` and then use that type to pass around your
delayed import or create a global to hold the import().

**Comment by Shmiddty** [comment] 2021-08-15 21:34
I'm having the same issue with a non-typescript project using svelte and svelte-pixi. 

It appears that it might be related to the commonjs loader?

```
3:29:08 PM [vite] Error when evaluating SSR module /node_modules/svelte-pixi/dist/Container.svelte:
ReferenceError: self is not defined
    at Object.<anonymous> (../node_modules/@pixi/polyfill/dist/cjs/polyfill.js:16:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (../node_modules/pixi.js/dist/cjs/pixi.js:12:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
self is not defined
```

**Comment by bigtimebuddy** [comment] 2021-08-15 22:36
There are a few instances of using `self` inline in polyfills, for instance:

https://github.com/pixijs/pixijs/blob/7ee2be5cf88bb990166db10cfb017e37aa2cbbb1/packages/polyfill/src/Promise.ts#L4-L7

It's possible to [create your own PixiJS bundle](https://pixijs.io/customize) that excludes polyfill (especially if you don't care about IE 9-11)

There may be other places, but polyfills is likely the prime offender.

**Comment by eXponenta** [comment] 2021-08-17 07:44
Pixi requiring a right context (browser), you cannot use it (include imports) without browser context, because pixi use global invocation for registering a plugins and modules (this is why window and self is used).

You can tring use pixi modules instead of bundle (use direct imports from @pixi/ except of pixi.js )  and register plugins manually.

Or you can try use a native dynamic imports (without babel/webpack) because pre-evaluation sometimes broking execution order.

About tests:
Test not use all packages in one context, it import packages one by one, and not link together.
And tests not include polyfills.

**Comment by Shmiddty** [comment] 2021-08-17 19:39
is `import { Application } from '@pixi/app';` correct? I'm still seeing `self is not defined` as an error.

**Comment by bigtimebuddy** [comment] 2021-08-17 19:56
@Shmiddty what's the stack for that? Where's the `self` coming from?

**Comment by Shmiddty** [comment] 2021-08-17 20:10
svelte (using JS), svelte-pixi, and pixi. same error as above

**Comment by einarpersson** [comment] 2021-08-19 06:43
Thanks for all the answers!

So the reason we have problems with [SvelteKit](https://kit.svelte.dev/), [Next.js](https://nextjs.org/) and other SSR-frameworks is that _"pixi use global invocation for registering a plugins and modules"_, is that a correct conclusion?

If that is the case, **would it be possible for pixi.js to do some kind of check for browser-context** before doing this, and fail gracefully if the browser is not available?

I think it would be very beneficial for the adoption of pixi.js since many new users will use these new modern frameworks.

**Comment by bigtimebuddy** [comment] 2021-08-19 19:03
I did a quick check importing pixi.js into Node.js directly, and there are only a handful of few places internally that will need to be fixed in order to not error on import. These are:

* polyfills
* settings: `isMobileCall(self.navigator);`
* core : `Texture.EMPTY` and `Texture.WHITE` creation
* loader useXdr : `!!(self.XDomainRequest && !('withCredentials' in (new XMLHttpRequest())));`
* loader : `var Url = self.URL || self.webkitURL;`
* text : `TextMetrics._canvas` & `TextMetrics._context` creation
* compressed-textures : `CompressedTextureLoader.add`

This is a very solvable problem, if we don't statically do these things.

PRs welcome to fix, this is not a high priority for the project but if anyone here wants to champion this, I'm sure other folks would find it useful.

**Comment by derolf** [comment] 2021-08-19 20:16
Use a dynamic import.

**Comment by ShukantPal** [comment] 2021-08-27 23:15
@bigtimebuddy Isn't it undesirable for PixiJS to render on the server because SSR only sends down HTML and not the canvas contents?

**Comment by einarpersson** [comment] 2021-09-01 07:19
> @bigtimebuddy Isn't it undesirable for PixiJS to render on the server because SSR only sends down HTML and not the canvas contents?

Just to clarify my intentions: I have never proposed or asked for Pixi itself to render on the server. I've just asked for not throwing in a server environment because it makes it easier to work with. Sveltekit runs both on server and on client so I don't really care if it actually does something on the server, in this instance.

But if it is impossible as @derolf implied then and never going to happen then.. that is that

**Comment by lewiji** [comment] 2021-09-21 11:09
Same issue here on a custom SSR solution, using `react-pixi`. `react-pixi` behaves normally in a server environment, but importing any components, filters or other modules from the base `@pixi` or `pixi.js` packages results in the build failing to run.

Similar to @einarpersson, I'm not interested in getting Pixi to render in a server environment, as that would be insane (I guess a use case could be game streaming or something, but that's not something I'm interested in nor would I expect Pixi to support it realistically).

Our game runs in a serverless environment (App Engine) with a tight coupling between server/client versions. Since there may be multiple instances running different versions at any given time, the server bundle (a Node application) contains/imports the code of the clientside app bundle (a React application which contains some Pixi elements) and can server-side render parts of the app bundle into a custom package which is delivered to the player's browser depending on their request and auth status.

So really, the fact that Pixi is included in the clientside code should be irrelevant, since I'm not *running* any Pixi code on the server environment. The issue seems to be (my best guess, as I haven't yet tracked down the exact problem) that Pixi runs some setup code outside of its module scope immediately upon being imported, rather than on instantiation. It's this that causes the server to fail, and I don't believe that it should be impossible to prevent this.

I've gotten around this so far using a hacky `async/await import` mechanism in a custom hook like so:

```
import { useState, useEffect } from "react";

export default function usePixi() {
  const [pixi, setPixi] = useState();

  useEffect(() => {
    (async () => {
      if (!pixi) {
        await import("@inlet/react-pixi/legacy").then((p) => {
          setPixi(p);
        });
      }
    })();
  }, []);

  return pixi;
}
```

Rather than importing Pixi directly, my components can use this hook to get a reference to the library instead. This ensures that the Pixi bundle isn't actually loaded until a clientside component actually renders and triggers the hook, and so whatever code is being run outside of module scope doesn't get triggered on the serverside.

This works for some things, however, for example trying to use a WebGL Filter doesn't seem to work via this method and I have to import it the usual way, which then causes the bundle to fail in the same way.

**Comment by mszu** [comment] 2021-09-24 10:51
I'll add another +1 for interest in getting this patched correctly in this repository.

That said, I went ahead and put together a shim that stubs out everything `pixi.js` tries to do when you import it. As long as the shim gets imported before any Pixi dependencies, everything works (that I've tried, with SvelteKit anyway). Note that this kind of solution is brittle since it depends on the packaging/bundling to not reorder a Pixi dependency ahead of the shim, and at least for SvelteKit this seems like it's under active development. Having the use of `self`, `window`, `document.createElement`,`canvas.getContext()`, etc. made conditional in this library would be much better.

npm library: [@mszu/pixi-ssr-shim](https://www.npmjs.com/package/@mszu/pixi-ssr-shim)
example SvelteKit app: [https://github.com/mszu/svelte-kit-pixi-sample](https://github.com/mszu/svelte-kit-pixi-sample)

Hope this helps!

**Comment by JoshuaPelealu** [comment] 2021-12-15 13:02
I have found a way to make this a little better, instead of using `self` or `window` by itself, it might actually be better to use `globalThis` because in a node environment, it is usually declared

**Comment by wyattzheng** [comment] 2021-12-26 07:17
@JoshuaPelealu +1

**Closed** 2022-02-06 17:08 UTC

**Comment by TrevorHinesley** [comment] 2022-05-06 22:01
I'm on 6.3.2 and still experiencing this when load a page in local dev with SvelteKit. Refreshing fixes it like before.

```
4:58:23 PM [vite] Error when evaluating SSR module /src/lib/utils/pixi/classExtensions.ts:
ReferenceError: self is not defined
    at Object.<anonymous> (/Users/me/video-editor/node_modules/@pixi/settings/dist/cjs/settings.js:17:29)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/me/video-editor/node_modules/@pixi/display/dist/cjs/display.js:12:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

**Comment by bigtimebuddy** [comment] 2022-05-06 22:29
@TrevorHinesley can you please create a simple reproduction?
