### ISSUE TITLE
Improve aliased line rendering

### ISSUE THREAD

**Issue by Kurtil** [pixijs/pixijs#7511] opened 2021-05-28 13:17 UTC
I used canvas2d API first to draw some building map. The drawing was pretty smooth even with small lines.

I had to switch to pixi with the Graphics API because of performance issues.

However, even with the renderer antialias turned on, small lines are dashed:

![aliased-lines](https://user-images.githubusercontent.com/22523482/119989527-8f639f80-bfc7-11eb-8d67-002ad620db4e.gif)

Is there any solution to fix this problem ?

I found this https://github.com/pixijs/pixijs/issues/5714 but seems very low level...

**Comment by ivanpopelyshev** [comment] 2021-05-28 13:38
> Is there any solution to fix this problem ?

People search for this solution for all 10 years of webgl. I'm making one, do you want to put extra bounty on it?

**Comment by ivanpopelyshev** [comment] 2021-05-29 11:47
You can try port https://wwwtyro.net/2019/11/18/instanced-lines.html to pixi

**Comment by SukantPal** [comment] 2021-05-29 16:25
Are you using `antialias: true, autoDensity: true, resolution: window.devicePixelRatio` in your application options?

**Comment by Amoki** [comment] 2021-05-31 14:33
Hi, I'm @Kurtil colleague.

@SukantPal, none of these change anything :(

@iivanpopelyshev We can put a bounty up to €500. Do you use any service to manage bounties?

**Comment by SukantPal** [comment] 2021-05-31 15:02
Can you create a small reproduction? cc @bigtimebuddy for the bounty

**Comment by bigtimebuddy** [comment] 2021-05-31 16:46
@Amoki here some information about sponsoring bounties: https://github.com/pixijs/pixijs/wiki/Bounties#--sponsoring we use OpenCollective to manage the payouts.

**Comment by Amoki** [comment] 2021-06-01 10:08
Here is a simple example triggering the bug: https://jsfiddle.net/GaetanLagier/w5hfmc6r/50/
Here is the same example with canvas API, with the expected result: https://jsfiddle.net/GaetanLagier/av6buojt/16/

@bigtimebuddy, Can you flag the issue with a bounty of 500€ (or $600)?

**Comment by SukantPal** [comment] 2021-06-01 13:22
Hmm, the canvas version also gets dashes on my iPad. Also, you didn't add `autoDensity: true` in your WebGL version.

**Comment by Kurtil** [comment] 2021-06-01 13:29
Unfortunately `autoDensity: true` does not change anyhting :/

**Comment by Amoki** [comment] 2021-06-01 14:05
I updated the version to use `autoDensity: true` https://jsfiddle.net/GaetanLagier/w5hfmc6r/56/

**Comment by ivanpopelyshev** [comment] 2021-06-09 10:52
Is that better? https://codesandbox.io/s/xenodochial-neumann-z4skv?file=/src/index.js

**Comment by Kurtil** [comment] 2021-06-09 13:59
Seems very promising! :D

I supposed "pixi.js-legacy" is the version 6.0.4.
I replaced my old Graphics with SmoothGraphics of your pixi-candles file.

I've seen four issues.

- Discontinued lines seems joined:

Before the change:
![Screenshot 2021-06-09 at 15 28 19](https://user-images.githubusercontent.com/22523482/121363697-76e47500-c937-11eb-8309-495ce5bc4913.png)

After the change:
![Screenshot 2021-06-09 at 15 28 45](https://user-images.githubusercontent.com/22523482/121363693-75b34800-c937-11eb-820b-e516f70a3170.png)

- top lines do not hide back lines anymore:

Before the change:
![Screenshot 2021-06-09 at 15 24 36](https://user-images.githubusercontent.com/22523482/121363038-df7f2200-c936-11eb-9ffb-f1b75822c93c.png)

After the change:
![Screenshot 2021-06-09 at 15 24 10](https://user-images.githubusercontent.com/22523482/121363045-e0b04f00-c936-11eb-8d1a-d67f8365c70c.png)

- Lines are very blurry:

Before the change:
![Screenshot 2021-06-09 at 15 28 31](https://user-images.githubusercontent.com/22523482/121363694-764bde80-c937-11eb-876c-f2e6fe3e7f51.png)

After the change:
![Screenshot 2021-06-09 at 15 28 50](https://user-images.githubusercontent.com/22523482/121363686-74821b00-c937-11eb-892b-08406daf4c99.png)

- Lines are still dashed with some angles:
I changed your example with these values:
```javascript
graphics.lineStyle(1, 0, 1);

graphics.moveTo(0, 150);
graphics.lineTo(600, 150);

graphics.rotation = 0.06
```

This line is drawn:

![Screenshot 2021-06-09 at 15 58 13](https://user-images.githubusercontent.com/22523482/121368644-81a10900-c93b-11eb-8956-2567a4991389.png)

**Comment by ivanpopelyshev** [comment] 2021-06-09 14:17
I just didnt code everything, I made architecture that solves that issue but i didnt put all the algos for joints/smooth/optimization in it

Can you make the separate codesandbox with all those issues so I can debug them?

**Comment by ivanpopelyshev** [comment] 2021-06-09 15:02
OK, done with the lines/line. Please give me the code for bad smoothed squares and lines

**Comment by Kurtil** [comment] 2021-06-09 15:41
The blur seems to appear with scaling:

```javascript
import "./styles.css";

import * as PIXI from "pixi.js-legacy";
import { SmoothGraphics } from "./pixi-candles.es.js";

const renderer = new PIXI.Renderer({
  backgroundColor: 0xffffff,
  resolution: window.devicePixelRatio || 1,
  antialias: false,
  autoDensity: true
})

document.body.appendChild(renderer.view);

const stage = new PIXI.Container()

// Smooth rectangle
const smoothGraphic = new SmoothGraphics();

smoothGraphic.lineStyle(5, 0, 1);
smoothGraphic.drawRect(20, 20, 50, 50);
smoothGraphic.endFill();

stage.addChild(smoothGraphic);

// Original rectangle
const graphics = new PIXI.Graphics();

graphics.lineStyle(5, 0, 1);
graphics.drawRect(100, 20, 50, 50);
graphics.endFill();

stage.addChild(graphics);

const transform = new PIXI.Matrix();
transform.scale(5, 5)

renderer.render(stage, {
  transform 
})
```

![Screenshot 2021-06-09 at 17 40 44](https://user-images.githubusercontent.com/22523482/121385908-d51a5380-c949-11eb-887c-d73a8c4ea077.png)

**Comment by ivanpopelyshev** [comment] 2021-06-09 15:55
```
renderer.render(stage, {
  transform 
})
```
my AA doesnt support scale in transform yet, but yeah, i can add it :)

**Comment by ivanpopelyshev** [comment] 2021-06-09 16:04
OK, done, though only uniform scale supported (it has to be the same by X and Y). Translations/rotations are ok.

Also you have width=5 that means its half-integer, and your scale is 5, so its a bit blurry on the edge in the end. if either of those were even it will be perfect sharp :)

**Comment by ivanpopelyshev** [comment] 2021-06-10 15:16
Added Bevel, for now it turns on big angles.

**Comment by Amoki** [comment] 2021-06-10 15:18
How can we try the latest versions? The link seems stuck to the first version

**Comment by ivanpopelyshev** [comment] 2021-06-10 16:24
Strange , i thought i updated it in codesandbox.. you can take it from github gameofbombs/pixi-candles, npm run build, take file from "lib"

**Comment by ivanpopelyshev** [comment] 2021-06-10 21:58
Miter/Bevel/Round works. Now to caps.

**Comment by Kurtil** [comment] 2021-06-11 08:40
You are getting closer! :D

i just spotted that textures seem dimmed... In your example with the new lib build from your repository, I just add a fill color and another rectangle behind the first one:

```javascript
graphics.lineStyle(1, 0, 1);
graphics.beginFill(0xFF0000, 1)
graphics.drawRect(150, 150, 300, 300);
graphics.endFill();

const graphicsBehind = new SmoothGraphics();
graphicsBehind.lineStyle(6, 0x00FFFF, 1);
graphicsBehind.drawRect(50, 200, 300, 50);

app.stage.addChild(graphicsBehind);

app.stage.addChild(graphics);
```

Texture are not fully opaque:

![Screenshot 2021-06-11 at 10 38 53](https://user-images.githubusercontent.com/22523482/121658012-3a348d00-caa1-11eb-8d3d-2e165766db39.png)

**Comment by ivanpopelyshev** [comment] 2021-06-11 09:27
Oh, thanks! gonna fix it now

**Comment by ivanpopelyshev** [comment] 2021-06-11 09:35
There was a regression, now its gone. Give me screens of complex stages like the one in first post please :)

**Comment by Kurtil** [comment] 2021-06-11 10:01
It is smoother ;)

![42d26aa6e5999d3ec1b6413568041262](https://user-images.githubusercontent.com/22523482/121669260-6dc8e480-caac-11eb-971b-8ee9f99a4f51.gif)

**Comment by Kurtil** [comment] 2021-06-11 10:06
![e54209aa16b00cd45b1f907c22663751](https://user-images.githubusercontent.com/22523482/121670013-4888a600-caad-11eb-8b70-fd068e0eda14.gif)

It seems that texture fill is broken at small zoom levels :/ 

Also I am not able to fill object with custom texture. `beginTextureFill` always use the Pixi white texture...

**Comment by ivanpopelyshev** [comment] 2021-06-11 11:03
Because there is no texture fill :) yet.

**Comment by ivanpopelyshev** [comment] 2021-06-11 11:05
Yep, fill that had no strokes at the same path might go wrong, im working on it. I'll make a switch that turns off AA on fill completely

**Comment by eXponenta** [comment] 2021-06-11 11:35
You always can use Graphics for fills and Smooth Graphics for lines.
Because there are not way do all is precise for every scale ratio.
The implementation has precision limit and can (and will) bugged on devices that not has `highp`

**Comment by ivanpopelyshev** [comment] 2021-06-11 14:22
OK, new changes.

It seems my AA on fills isnt that good, so i made it optional

```js
beginFill(1, 0.5) // as always
beginFill(1, 0.5, true) // AA on fills, experimental!!!!!
beginTextureFill({... , smooth:true}); //same for textures
```

sadly, there is no texture fill yet, maybe will be in a few hours, but for now im working on caps

**Comment by ivanpopelyshev** [comment] 2021-06-13 11:20
Butts are ready. https://codesandbox.io/s/hhaa-smoothing-line-joints-t3b3n?file=/src/index.js

Is texture fill the only thing left for you?

**Comment by Kurtil** [comment] 2021-06-15 09:20
Yep ! :)

**Comment by ivanpopelyshev** [comment] 2021-06-17 14:13
New repo is here:  https://github.com/pixijs/graphics-smooth , and for umd its `PIXI.smooth` for now, otherwise `import {SmoothGraphics} from './pixi-graphics-smooth.es.js'` should work

`beginTextureFill()` doesnt work with `{smooth:true}`,so if you need smoothed texture fills - you'll have to wait.

**Comment by ivanpopelyshev** [comment] 2021-06-17 15:20
Actually, i published `@pixi/graphics-smooth` version `0.0.1`

**Comment by ivanpopelyshev** [comment] 2021-06-17 22:41
Example moved to https://pixijs.io/examples/#/plugin-graphics-smooth/join-cap.js

**Comment by bigtimebuddy** [comment] 2021-06-17 23:43
I'm going to close this issue. @ivanpopelyshev has created a great solution here and any further debugging or issues should be reported on the graphics-smooth repo (link above).

@Amoki for the bounty, assuming this meets your needs, you can coordinate with Ivan on payout directly, or if you'd like, we can to do it through Pixi's Open Collective. Let me know if you need additional help.

**Closed by bigtimebuddy** 2021-06-17 23:43 UTC
Labels: 💰Bounty

**Comment by ivanpopelyshev** [comment] 2021-06-24 16:12
@Kurtil can you please post current list of bugs that need fix in https://github.com/pixijs/graphics-smooth ? btw i just updated it regarding resolution

**Comment by Kurtil** [comment] 2021-06-25 08:24
Ok. I will update my viewer with it and let you know ;)

**Comment by Amoki** [comment] 2021-07-01 09:35
@ivanpopelyshev @bigtimebuddy I'm not sure about how to proceed with Open Collective. Can you contact me at hugo[you know what]bimdata.io ?

**Comment by ivanpopelyshev** [comment] 2021-07-01 10:10
OK, I contacted you :) Tell me if there are any problems.

**Comment by xpluscal** [comment] 2024-07-24 07:17
@ivanpopelyshev @eXponenta any new takes on how to do this in Pixi 8?

**Comment by eXponenta** [comment] 2024-07-24 08:38
> @ivanpopelyshev @eXponenta any new takes on how to do this in Pixi 8?

No any plans for porting graphics-smooth to webgpu runtime (pixi 8 )

**Comment by ivanpopelyshev** [comment] 2024-07-24 10:05
New takes:

1/ WebGPU does not support instancing intersection , means we cant just read prev and next points thgouth vertex buffer . it means new implementation has to use storage buffer for WebGL?2 and storage buffer for WebGPU

2. Its not a problem anymore to port the shader, we have a new shader compiler that can do it.

I can start doing it in two weeks, I think
