### ISSUE TITLE
Bug: pixi.js-legacy extensions mechanism works incorrectly with pixi-spine

### ISSUE THREAD

**Issue by f0nar** [pixijs/pixijs#9779] opened 2023-10-23 10:36 UTC
### Current Behavior

I cannot use `pixi.js-legacy` with `pixi-spine`. If I run next code snippet
```
import 'pixi-spine';
import * as PIXI from "pixi.js-legacy";
import { Spine } from "pixi-spine";

PIXI.extensions

const run = async () => {
  const app = new PIXI.Application<HTMLCanvasElement>({
    background: "#1099bb",
    resizeTo: window
  });
  
  document.body.appendChild(app.view);

  PIXI.Assets.add('spineData', 'skeleton.json');
  PIXI.Assets.add('spineAtlas', 'skeleton.atlas');
  await PIXI.Assets.load(['spineData', 'spineAtlas']).then(console.log); // check screenshot with output below

  const spineResource = PIXI.Assets.get('spineData');
  const spine = new Spine(spineResource.spineData);
  app.stage.addChild(spine);
  
  const bounds = spine.getBounds(true);
    
  spine.position.set((app.view.width - bounds.width) / 2 - bounds.left, (app.view.height - bounds.height) / 2 - bounds.top);
  spine.state.setAnimation(0, "animation", true);
  spine.autoUpdate = true;
};

run();
```
I receive errors in the console due to unparsed data and next object in console 
![image](https://github.com/pixijs/pixijs/assets/48058174/61d2363a-677b-4a92-a296-24dcb9041b02)
As you can see that atlas is not parsed at all and spine json file is loaded as simple json and it does not have `spineData` property.
As I understood, problem is that `pixi-spine` registers its loaders not to the same `extensions` package that `pixi.js-legacy` uses.

### Expected Behavior

Have ability to simply use `pixi-spine` with `pixi.js-legacy` or have exports in `pixi-spine` to register loaders manually

### Steps to Reproduce

Install `pixi-spine`:`4.0.4`
Install `pixi.js-legacy`:`7.3.0`
Try to load and play spine

You can use my repo for testing https://github.com/f0nar/pixi.js-legacy-pixi-spine/tree/main

### Environment

- **`pixi.js-legacy` version**: *7.3.0*
- **`pixi-spine` version**: *4.0.4*
- **Browser & Version**: *Chrome 118*
- **OS & Version**: *macOS Ventura 13.5.2*

### Possible Solution

As quick fix I exported atlas and spine loaders extensions from `pixi-spine` and called `PIXI.extensions.add` with them in my `index.ts`, where `PIXI` is `pixi.js-legacy` import

### Additional Information

@miltoncandelero  the same is relevant to https://github.com/miltoncandelero/spine-runtimes/tree/spine-pixijs/spine-ts/spine-pixi

**Comment by miltoncandelero** [comment] 2023-10-23 11:31
Do we have mesh in pixi legacy? Without mesh spine is limited to regions (sprites) 🤔

Spine-pixi doesn't use sprites but all meshes🤔

Iirc pixi-spine tries to use sprites if it detects one

**Comment by f0nar** [comment] 2023-10-23 13:06
> Do we have mesh in pixi legacy? Without mesh spine is limited to regions (sprites) 🤔
> 
> Spine-pixi doesn't use sprites but all meshes🤔
> 
> Iirc pixi-spine tries to use sprites if it detects one

Sorry, I didnt get your point. As I see, problem is that atlas and spine loaders that `pixi-spine` should register to `PIXI.extensions` dont rich loading and parsing pipelines. It is because `pixi.js-legacy` has its own custom `extensions` package in `node_modules`. Is that right?

**Comment by f0nar** [comment] 2023-10-26 12:31
@miltoncandelero any thoughts on that? I create PR that can unblock me for now https://github.com/pixijs/spine/pull/525. Could you check it please?

**Comment by miltoncandelero** [comment] 2023-10-26 12:49
@Zyie do you have some insight on why it doesn't work with pixi legacy?
I don't see what could be the difference 🤔

**Comment by f0nar** [comment] 2023-10-26 13:38
dependencies as I understand. `pixi-spine` refers to `{project_root}/node_modules/@pixi` and `pixi.js-legacy` refers to its own `{project_root}/node_modules/pixi.js-legacy/node_modules/@pixi`, so in the result loaders dont reach correct scope

**Comment by bigtimebuddy** [comment] 2023-10-26 13:44
This is likely an issue with npm issue installing Pixi and the spine plugin. It should be deduping the dependencies. The fact that they are nested makes me think something didn't install correctly. Try uninstalling Pixi and Pixi-spine, then install them at the same time. See https://github.com/pixijs/pixijs/wiki/Upgrading-PixiJS

**Comment by f0nar** [comment] 2023-10-26 13:50
> This is likely an issue with npm issue installing Pixi and the spine plugin. It should be deduping the dependencies. The fact that they are nested makes me think something didn't install correctly. Try uninstalling Pixi and Pixi-spine, then install them at the same time. See https://github.com/pixijs/pixijs/wiki/Upgrading-PixiJS

are you sure that it is relevant to `pixi.js-legacy`? what should I reinstall in my case?

**Comment by bigtimebuddy** [comment] 2023-10-26 14:46
On you example repo, I did this:
```
npm uninstall pixi.js-legacy pixi-spine
npm install pixi.js-legacy pixi-spine
```
And that fixed the issue. You can also try to delete your node_modules and lock file. Would also have a similar result. This issue can happen if you install the pixi.js-legacy _then_ pixi-spine. By installing them at the same time, you can more easily resolve their shared packages.

**Comment by f0nar** [comment] 2023-10-26 15:27
> On your example repo, I did this:
> 
> ```
> npm uninstall pixi.js-legacy pixi-spine
> npm install pixi.js-legacy pixi-spine
> ```
> 
> And that fixed the issue. You can also try to delete your node_modules and lock file. Would also have a similar result. This issue can happen if you install the pixi.js-legacy _then_ pixi-spine. By installing them at the same time, you can more easily resolve their shared packages.

What can I do if I need to lock version of pixi?  I need exactly `pixi.js-legacy`:`7.3.0`. This solution install the latest ones

**Comment by bigtimebuddy** [comment] 2023-10-26 15:39
In npm@9, you can use `overrides` to declare how versions should resolve for packages (yarn has had a similar `resolutions` mechanism for awhile). Here's how you'd do it in your project:

```json
{
  "name": "pure-pixi",
  "version": "1.0.0",
  "description": "",
  "private": "true",
  "keywords": [],
  "author": "glebv",
  "license": "UNLICENSED",
  "scripts": {
    "dev": "vite --open",
    "preview": "vite preview",
    "test": "tsc"
  },
  "dependencies": {
    "pixi-spine": "4.0.4",
    "pixi.js-legacy": "7.3.0"
  },
  "devDependencies": {
    "typescript": "^5.2.2",
    "vite": "^4.4.9"
  },
  "type": "module",
  "overrides": {
    "pixi-spine": {
      "@pixi/assets": "7.3.0",
      "@pixi/core": "7.3.0",
      "@pixi/display": "7.3.0",
      "@pixi/graphics": "7.3.0",
      "@pixi/mesh": "7.3.0",
      "@pixi/mesh-extras": "7.3.0",
      "@pixi/sprite": "7.3.0"
    }
  }
}
```

**Comment by bigtimebuddy** [comment] 2023-10-26 21:22
I'm going to close this issue as it's not a bug. If you need more help with version resolution and npm, please open a discussion thread.

**Closed by bigtimebuddy** 2023-10-26 21:22 UTC
Labels: 👍 Not A Bug

**Comment by f0nar** [comment] 2023-10-27 09:46
sure. thanks for your help!
