### ISSUE TITLE
pixi crashed when set text-node's fontSize to 0

### ISSUE THREAD

**Issue by hbli1** [pixijs/pixijs#7647] opened 2021-07-28 10:46 UTC
Uncaught DOMException: Failed to execute 'getImageData' on 'OffscreenCanvasRenderingContext2D': The source width is 0.

in this function: TextMetrics.measureFont

is that a bug?

**Comment by eXponenta** [comment] 2021-07-28 11:38
Not, this is UB.
You use fontSize = 0, what you want see?

**Comment by bigtimebuddy** [comment] 2021-07-28 14:03
Duplicate of #7607

**Closed** 2021-07-28 14:03 UTC
