### ISSUE TITLE
Bug: @Pixi/loader does not install latest 6.5.10 

### ISSUE THREAD

**Issue by jefe-spain** [pixijs/pixijs#9544] opened 2023-07-13 10:56 UTC
### Current Behavior

The package '@pixi/loaders' is currently at version 6.5.10 in its latest release for v6. However, when installing it through npm using 'npm install', version 6.5.9 is installed instead. This can cause issues with other libraries that depend on '@pixi/loaders' because it includes peerDeps based on its version number.

### Expected Behavior

The expected behavior for "@pixi/loaders" is that it should install the latest version available for its major release. This means that when using a package manager like npm to install "@pixi/loaders", it should fetch and install the most recent version that is compatible with the specified major version. For example, if the major version is 6, the package manager should install the latest version within the 6.x.x range, in this case 6.5.10

### Steps to Reproduce
If we try to do a clean install for `@pixi/loaders: "^6.1.0" ; It bring 6.5.9 into node_modules.

Also in a clean package.json, if we use a library that depends on '@pixi/loaders'

`{
  "name": "pixi-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@pixi-spine/loader-base": "~3.1.0"
  }
}`

It will result on (see screenshot attached)

<img width="818" alt="Screenshot 2023-07-13 at 12 54 13" src="https://github.com/pixijs/pixijs/assets/1828187/5cc2120e-54ae-45ea-becf-15ea9f8da950">

### Additional Information

I believe @pixi/polyfill will present the same behaviour due to the latest tag pointing to 6.5.9

**Comment by bigtimebuddy** [comment] 2023-07-13 13:39
This has been fixed. Duplicate of #9108

The issue is we removed loaders, polyfill and interaction from v6. When we publish the `latest` tag doesn't get update and therefore takes priority over other published versions. I'll add a post publish step to our build process in v6 to fix this.

**Closed** 2023-08-08 13:06 UTC

**Comment by skwidhubz** [comment] 2023-11-07 23:17
So, what is used in place of Loader?

**Comment by bigtimebuddy** [comment] 2023-11-08 00:19
@skwidhubz Assets has replaced Loader for loading resources.

**Comment by skwidhubz** [comment] 2023-11-08 02:42
>Many thanks! @skwidhubz Assets has replaced Loader for loading resources.
