### ISSUE TITLE
TS2339: missing properties 'interactive', 'on' for PIXI.Container

### ISSUE THREAD

**Issue by abodelot** [pixijs/pixijs#7816] opened 2021-09-20 22:28 UTC
Hi, after upgrading from pixi 5 to pixi 6, I got a typescript error about event-related properties not defined anymore on `PIXI.Container` class.

Minimal code example:
```ts
import * as PIXI from 'pixi.js';

class Foobar extends PIXI.Container {
  constructor() {
    super();
    this.interactive = true;
    this.on('pointertap', () => {
      console.log('hello');
    });
  }
}
```

With `pixi.js 6.1.3`, `tsc` gives the following error:

```
src/Foobar.ts:6:10 - error TS2339: Property 'interactive' does not exist on type 'Foobar'.
6     this.interactive = true;
           ~~~~~~~~~~~
src/Foobar.ts:7:10 - error TS2339: Property 'on' does not exist on type 'Foobar'.
7     this.on('pointertap', () => {
           ~~
```

This seems like a false positive, because those properties work as intended when ignoring `tsc` errors.

They are also listed in documentation: https://pixijs.download/release/docs/PIXI.Container.html#interactive

With `pixi.js 5.2.1`, `tsc` does not give any error with the same code.

- **typescript**: 4.4.3
- **ts-loader**: 9.2.5
- **OS & Version**: Ubuntu 20.04

**Comment by bigtimebuddy** [comment] 2021-09-20 22:31
Please make sure v5 is _completely_ removed from your package-lock.json or yarn.lock file. Having a mix of v5 and v6 will break types in this way.

**Comment by bigtimebuddy** [comment] 2021-09-20 22:33
Closing this, as it's likely duplicate of either #7505 or #7685

**Closed by bigtimebuddy** 2021-09-20 22:33 UTC

**Comment by abodelot** [comment] 2021-09-20 22:44
Thank you @bigtimebuddy for fast reply!

Although unrelated to pixi version upgrade, you provided the fix in linked issues (`esModuleInterop: true` in tsconfig :tada:).
