### ISSUE TITLE
Bug: Setting an empty array to the filters will cause the position to shift(v8)

### ISSUE THREAD

**Issue by yungzhu** [pixijs/pixijs#10057] opened 2024-01-04 07:53 UTC
### Current Behavior

https://www.pixiplayground.com/#/edit/UcZI52ouoK6N-eCOe-UUE

1. Setting an empty array to the filters will cause the position to shift

![image](https://github.com/pixijs/pixijs/assets/2418199/800e7560-7b7b-437c-bde7-c50d7c969f40)

### Expected Behavior

https://www.pixiplayground.com/#/edit/UcZI52ouoK6N-eCOe-UUE

### Steps to Reproduce

https://www.pixiplayground.com/#/edit/UcZI52ouoK6N-eCOe-UUE

### Environment

- **`pixi.js` version**: *e.g. v8rc*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by zjkmxy** [comment] 2024-01-04 16:35
Thank you for bringing this out. This bug troubled me a lot.
To provide more information, the code I'm using looks like follows:
```typescript
import * as PIXI from "pixi.js";

(async () => {
  const app = new PIXI.Application();
  await app.init({ background: "#1099bb", resizeTo: window });

  document.body.appendChild(app.canvas);

  // create a new Sprite from an image path
  const texture = await PIXI.Assets.load("https://pixijs.com/assets/bunny.png");
  const bunny = PIXI.Sprite.from(texture);

  // center the sprite's anchor point
  bunny.anchor.set(0.5);
  // move the sprite to the center of the screen
  bunny.x = app.screen.width / 2;
  bunny.y = app.screen.height / 2;

  const stage = new PIXI.Container();
  stage.filters = [];  // L1
  app.stage.addChild(stage);

  const container = new PIXI.Container();
  container.addChild(bunny);
  const filter = new PIXI.ColorMatrixFilter();
  container.filters = [filter];  // L2

  const wrapper = new PIXI.Container();
  wrapper.filters = [];
  const useWrapper = false;  // L3
  if(useWrapper) {
    wrapper.addChild(container);
    stage.addChild(wrapper);
  } else {
    stage.addChild(container);
  }

  const graphic = new PIXI.Graphics();
  stage.addChild(graphic);  // L4
  graphic.rect(-4000, -4000, 8000, 8000).fill({color: 0xffffff, alpha: 0});  // L5
})();
```

Observations:
- In the original code, the sprite is not shown at all.
- If we comment out L1, the sprite shows and the position is correct. Everything is normal.
  - This is the normal case when no empty array is used.
- If we change L2 to `container.filters = [];`, the sprite shows and the position is correct. Everything is normal.
  - This means if all filters are empty arrays, rendering is good.
- If we change L3 to `const useWrapper = true;`, the sprite shows but the position becomes (0,0);
  - This means a wrapper with an empty array can fix the visibility issue, but the position is still wrong.
- If we comment out L4, the sprite shows but the position becomes (0,0).
- If we change L5 to `graphic.rect(-200, -200, 8000, 8000).fill({color: 0xffffff, alpha: 0});`, the sprite shows but in the right, bottom corner, rather than the middle of screen.

**Comment by zjkmxy** [comment] 2024-01-05 18:30
I have played more and found that the issue is related to `skip`:
https://github.com/pixijs/pixijs/blob/071a61695eed40761230332f70cb1746f7a48641/src/filters/FilterSystem.ts#L141-L146

A filter array with filters all disabled will gave the same result as an empty array.

The reason I think could be that there is an offset applied to the global transform. When `skip` is true, FilterSystem does not directly modify `globalUniforms`. However, based on my observation, the coordinate origin is aligned with the last element drawn before `popFilter`. I'm not sure about the reason, though.

A quick fix could be to copy the input to the output when filters is empty instead of skipping the rendering.

**Comment by Zyie** [comment] 2024-01-08 10:53
This should be fixed in the latest rc.2

**Closed by Zyie** 2024-01-08 10:53 UTC
Labels: v8
