### ISSUE TITLE
Typescript Cannot find Offscreencanvas, OffscreenCanvasRenderingContext2D

### ISSUE THREAD

**Issue by zip87** [pixijs/pixijs#8191] opened 2022-02-17 15:55 UTC
I am attempting to compile Angular project with PixiJS 6.2.0. When I tried top compile it I would get an error referenced in this issue on the Pixi.js repo:

Error: node_modules/@pixi/core/index.d.ts:1535:45 - error TS2304: Cannot find name 'OffscreenCanvas'.
Error: node_modules/@pixi/text/index.d.ts:272:41 - error TS2304: Cannot find name 'OffscreenCanvas'.
Error: node_modules/@pixi/text/index.d.ts:273:49 - error TS2304: Cannot find name 'OffscreenCanvasRenderingContext2D'.
Error: node_modules/@pixi/text/index.d.ts:300:105 - error TS2304: Cannot find name 'OffscreenCanvas'.

Here is my package.json:
  "dependencies": {
    "@angular/animations": "~13.0.0",
    "@angular/cdk": "^13.0.3",
    "@angular/common": "~13.0.0",
    "@angular/compiler": "~13.0.0",
    "@angular/core": "~13.0.0",
    "@angular/forms": "~13.0.0",
    "@angular/material": "^13.0.3",
    "@angular/platform-browser": "~13.0.0",
    "@angular/platform-browser-dynamic": "~13.0.0",
    "@angular/router": "~13.0.0",
    "@microsoft/signalr": "^6.0.1",
    "@ngx-formly/core": "^5.10.27",
    "@ngx-formly/material": "^5.10.27",
    "@tailwindcss/typography": "^0.4.1",
    "@types/offscreencanvas": "^2019.6.4",
    "devextreme": "^21.2.3",
    "devextreme-angular": "^21.2.3",
    "devextreme-aspnet-data-nojquery": "^2.8.6",
    "devextreme-schematics": "^1.2.22",
    "font-awesome": "^4.7.0",
    "ngx-toastr": "^14.2.1",
    "pixi-cull": "^2.0.1",
    "pixi.js": "^6.2.0",
    "rxjs": "~7.4.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.0.1",
    "@angular/cli": "~13.0.1",
    "@angular/compiler-cli": "~13.0.0",
    "@ngx-formly/schematics": "^5.10.27",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "devextreme-cli": "latest",
    "devextreme-themebuilder": "^21.2.3",
    "jasmine-core": "~3.10.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "tailwindcss": "^2.2.19",
    "typescript": "~4.4.3"
  }

and my tsconfig.json:
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": false,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "esModuleInterop": true,
    "strictNullChecks": false,
    "target": "es2017",
    "module": "es2020",
    "lib": [
      "es2020",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true,
    "allowSyntheticDefaultImports": true,
    "noImplicitAny": false,
    "esModuleInterop": true,
  }
}

**Comment by bigtimebuddy** [comment] 2022-02-17 15:59
Duplicate of #8174

**Closed by bigtimebuddy** 2022-02-17 15:59 UTC
