### ISSUE TITLE
Under IOS15.4, it is found that the Pixi application has a ghosting problem when moving the Sprit or scaling and rotating after using Sprite.mask

### ISSUE THREAD

**Issue by MsLou** [pixijs/pixijs#8226] opened 2022-03-17 06:02 UTC
I upgraded my iPhone to IOS15.4, and found that the Pixi application has a problem of overlapping images after moving the Sprit or zooming and rotating after using the Sprite.mask

### Expected Behavior
In the IOS15.4 version, the zoom and rotation can be moved normally
### Current Behavior
There is a ghosting problem when moving Sprit or zooming and rotating, The playground is pretty self explanatory: https://www.pixiplayground.com/#/edit/DpgywzyuF17eBaS_YOBB2
### Possible Solution
No clue, but willing to explore solution if someone points me to the right direction or area.
### Steps to Reproduce
Use an iPhone device and the system version is IOS15.4 to open the link: https://www.pixiplayground.com/#/edit/DpgywzyuF17eBaS_YOBB2
### Environment

- **`pixi.js` version**: 6.2.2
- **Browser & Version**: Safari
- **OS & Version**: IOS15.4
- **Running Example**: https://www.pixiplayground.com/#/edit/DpgywzyuF17eBaS_YOBB2

**Comment by wwwtaras** [comment] 2022-03-17 08:25
in pixi.js version: 5.3.x - problem presents too

**Comment by ivanpopelyshev** [comment] 2022-03-17 09:48
Try turn off antialias

**Comment by luxaritas** [comment] 2022-04-10 18:30
See https://github.com/pixijs/pixijs/issues/8183

**Comment by Zyie** [comment] 2022-06-21 12:19
Duplicate of #8183

Current workaround is to disable `antialias`

**Closed by Zyie** 2022-06-21 12:19 UTC
