### ISSUE TITLE
Property 'on' does not exist on type 'Container'

### ISSUE THREAD

**Issue by merkuriy** [pixijs/pixijs#7505] opened 2021-05-24 14:56 UTC
```ts
const btn = new PIXI.Container();
btn.interactive = true;
btn.buttonMode = true;
btn.on('click', ev => console.log('btn.click', {ev});
```

### Expected Behavior
Without errors and warnings.

### Current Behavior
Getting Typescript error TS2339: Property 'on' does not exist on type 'Container'

### Possible Solution
```ts
import { EventEmitter } from 'eventemitter3';
```
instead
https://github.com/pixijs/pixijs/blob/45e767bae30896cac6e38ea6f86903423cc345d5/packages/utils/src/index.ts#L51

### Environment

- **pixi.js**: 6.0.4
- **Typescript**: 3.9.9
- **IDE**: VSCode 1.56.2
- **OS & Version**: Ubuntu 19.04

**Comment by bigtimebuddy** [comment] 2021-05-24 15:57
I was not able to reproduce this error: 
https://github.com/bigtimebuddy/pixi-v6-typescript-example/tree/verify-ee3

Please make sure your tsconfig.json sets `esModuleInterop` to `true`.

**Comment by merkuriy** [comment] 2021-05-24 16:29
Thanks @bigtimebuddy! It helped me `esModuleInterop: true`.

**Comment by bigtimebuddy** [comment] 2021-05-24 17:24
Great, glad that worked. Closing this. There are a few 3rd party dependencies of Pixi that require this so we are unlikely to change this requirement.

**Closed by bigtimebuddy** 2021-05-24 17:24 UTC
