### ISSUE TITLE
Bug: The requested module '/npm/@pixi/utils@7.1.3/+esm' does not provide an export named 'deprecation'

### ISSUE THREAD

**Issue by 8Observer8** [pixijs/pixijs#9210] opened 2023-02-24 23:08 UTC
### Current Behavior

Error message: The requested module '/npm/@pixi/utils@7.1.3/+esm' does not provide an export named 'deprecation'

### Expected Behavior

There should be no errors.

### Steps to Reproduce

- Go to https://www.jsdelivr.com/
- Type: pixi.js
- Select 7.1.3
- Click on ESM button
- Copy this link: https://cdn.jsdelivr.net/npm/pixi.js@7.1.3/+esm
- Use this link to set up Pixi.js with importmap:

index.html

```html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Example</title>
</head>

<body style="caret-color: transparent;">
    <canvas id="renderCanvas" width="400" height="400"></canvas>

    <!-- Since import maps are not yet supported by all browsers, it is
        necessary to add the polyfill es-module-shims.js
        Source: https://threejs.org/docs/index.html#manual/en/introduction/Installation -->
    <script async src="https://unpkg.com/es-module-shims@1.3.6/dist/es-module-shims.js"></script>
    <script type="importmap">
        {
            "imports": {
                "pixi-js": "https://cdn.jsdelivr.net/npm/pixi.js@7.1.3/+esm",
                "matter-js": "https://cdn.jsdelivr.net/npm/matter-js@0.19.0/+esm"
            }
        }
    </script>

    <script type="module" src="js/main.js"></script>
</body>

</html>
```

main.js

```js
import * as PIXI from "pixi-js";
import Matter from "matter-js";

console.log(`Matter.js version: ${Matter.version}`);

console.log(PIXI);
```

### Environment

- **`pixi.js` version**: *7.1.3*
- **Browser & Version**: *Chrome 110*
- **OS & Version**: *Windows 10*
- **Running Example**: 
- https://playcode.io/1230828
- https://plnkr.co/edit/HjnXqDsq9uOJxjkW

**Comment by bigtimebuddy** [comment] 2023-02-27 00:42
Duplicate of #9189, closing.

**Closed by bigtimebuddy** 2023-02-27 00:42 UTC
