### ISSUE TITLE
Bug: sprite's visible property has no effect within a particle container

### ISSUE THREAD

**Issue by patreeceeo** [pixijs/pixijs#9845] opened 2023-11-07 00:46 UTC
### Current Behavior

I created a sprite and added it to a particle container and set the sprite's visible property to false.

Result: the sprite is visible despite its visible property being set to false.

### Expected Behavior

Sprite is invisible.

### Steps to Reproduce

I created a minimal reproducing example using https://pixijs.com/playground.

```javascript
import { Application, Sprite, ParticleContainer } from 'pixi.js';

const app = new Application();

document.body.appendChild(app.view);

const bunny = Sprite.from('https://pixijs.com/assets/bunny.png');

const container = new ParticleContainer(1)

app.stage.addChild(container)

// move the sprite to the center of the screen
bunny.x = app.screen.width / 2;
bunny.y = app.screen.height / 2;

container.addChild(bunny);

app.ticker.add((delta) => {
    bunny.visible = false;
});
```

### Environment

- **`pixi.js` version**: 7.3.x
- **Browser & Version**: Chromium 119
- **OS & Version**: Ubuntu 20.04
- **Running Example**: N/A

### Possible Solution

More of a workaround: Check if sprite is rendering inside a particle container and if so, remove it when it shouldn't be visible.

```javascript
if(container) {
  if(!isVisible) {
    container.removeChild(sprite);
  } else {
    container.addChild(sprite);
  }
} else {
  sprite.visible = isVisible;
}
```

**Comment by gabrielliwerant** [comment] 2024-02-07 19:31
I have a very similar issue with the sprite alpha value. You can set the sprite alpha value once, but if you change it later, the particle container continues to show the original alpha value, even though if you inspect the sprite, it shows the correct alpha value.

Feels like a bug to me, but it's not clear from the documentation if this behavior is intended or not.

Here's my codepen: https://codepen.io/gliwerant/pen/GReBPad

**Comment by RecursiveVoid** [comment] 2024-04-15 10:16
First of all, its not a bug, its a feature since which one of the main feature of ParticleContainer is having less features at the end to gain more performance. Being lightweight is the key here.  To achieve such performance boost from particle container, you need to compromise from some of the features. Like rotation, masking, children, filters.. and some of the features like changing the alpha. 


Please check the **source code** of Container, DisplayObject and ParticleContainer. 

https://api.pixijs.io/@pixi/particle-container/src/ParticleContainer.ts.html#175
https://api.pixijs.io/@pixi/display/src/DisplayObject.ts.html#441
https://api.pixijs.io/@pixi/display/src/Container.ts.html#418

Especially the part **UpdateTransform();** you will see Container updates all the children (re-calculates the alpha etc.. at that process)  meanwhile the ParticleContainer has a simpler approach to maintain performance.

**Comment by gabrielliwerant** [comment] 2024-05-12 01:04
@RecursiveVoid Thanks for the information and the reply.

If the alpha cannot be changed in a `ParticleContainer`, by intent, why does it allow the value the on the sprite to change, instead of keeping it as it was before, or throwing some kind of error/warning? The lack of these features will leave developers confused and it's not clear what things are intended or oversights when reading source, as every program is incomplete and/or contains bugs.

The official docs further muddy this from the following line regarding tint: `When true, alpha and tint be uploaded and applied,` implying that the alpha value might change.

**Comment by GoodBoyDigital** [comment] 2024-11-09 22:05
hey there, going to close this out as we have a fresh implemenation of `ParticleContainer`that further seperates it from the default container (and gives us much more speed for it!) 

We have a plan to write a lot more guides for Pixi including `ParticleContainer`, for now I hope [this post](https://pixijs.com/blog/particlecontainer-v8) helps

**Closed by GoodBoyDigital** 2024-11-09 22:05 UTC
