### ISSUE TITLE
Application height than 4000, extract image return black image

### ISSUE THREAD

**Issue by Clear2** [pixijs/pixijs#8508] opened 2022-07-18 03:36 UTC
```js
let height = 1448*3
const app = new PIXI.Application({
    width: 750,
    height: height,
    forceCanvas: true,
    preserveDrawingBuffer: true
})

function getTexture(path) {
    const img = `/assets/${path}`
    return PIXI.Texture.from(img)
}

const container = new PIXI.Container()
app.stage.addChild(container);

for (let i = 0; i <1 ;i++) {
    const bg = new PIXI.Sprite(getTexture('bg.97a62c70.jpg'))
    bg.position.set(0, 1448*i)
    container.addChild(bg)
}
setTimeout(() => {
    const src = app.view.toDataURL()
    app.renderer.plugins.extract.canvas(container).toBlob((b) => {
        const img = document.querySelector('.img');
        // img.src = src
        img.src = URL.createObjectURL(b)
    }, 'image/png');
}, 1000)
```

### Expected Behavior
return app stage image

### Current Behavior
if  use app.view.toDataURL, container bg position not incorrect ,
when use  app.renderer.plugins.extract.canvas, will return black image 

### Possible Solution
height more than 4000

### Environment

- **`pixi.js` version**: _e.g. 4.7.1_
- **Browser & Version**: _e.g. Safari
- **OS & Version**: _e.g. iOS 13.1_
- **Running Example**: _url_

**Comment by bildungsroman** [comment] 2023-07-08 00:10
Were you ever able to resolve this? I'm using `const image = app.renderer.plugins.extract.image(app.stage, "image/png", 1.0);` and getting a similar issue.

**Comment by bigtimebuddy** [comment] 2023-07-08 00:17
Your code worked fine for me
https://jsfiddle.net/6qeo1bjm/

Does this reproduce for you with canvas and webgl or just canvas (like the example)?

Could you please create a runnable example that reproduces the issue?

**Comment by GoodBoyDigital** [comment] 2024-11-09 21:08
closing as this is an upstream issue due to the limits of the browser rather than pixi!

**Closed by GoodBoyDigital** 2024-11-09 21:08 UTC
Labels: 👯‍♀️ Needs Reproduction, 🐠 Upstream Bug
