### ISSUE TITLE
iOS 15.4 beta 2 Sprite mask not rendering correctly when antialias: true

### ISSUE THREAD

**Issue by takumane** [pixijs/pixijs#8183] opened 2022-02-11 11:29 UTC
### Expected Behavior
Sprite Mask to work when antialias: true as it does in iOS 15.3
### Current Behavior
On iOS 15.4, when using sprite mask and setting antialias: true on renderer (or PIXI.Application()), it appears old frame are not cleared and new frame keeps being rendered on top of each other. I can see the same behavior on https://pixijs.io/examples/#/masks/sprite.js when I add { antialiase: true }  to PIXI.Application(). Please see attached video.

### Possible Solution

I am not equipped enough to go deep into webgl debugging to understand what is causing this or how we can fix this. I don't even know how/where to report this bug to apple. Hopefully someone with more in-depth knowledge of how PIXI works can tell what the problem is, and if not fixing it, maybe report it to apple so they can address it before officially release iOS 15.4. I can imagine this breaks a lot of PIXI dependent apps / games.

https://user-images.githubusercontent.com/30465872/153583894-894b4da2-6ee1-4f2e-aea6-8fe57aadc4fe.mov

### Steps to Reproduce

Enable antialias on the renderer, use Sprite mask, and move the masked object around every frame.

### Environment

- **`pixi.js` version**: 6.2.2
- **Browser & Version**: Safari & Chrome
- **OS & Version**: iOS 15.4
- **Running Example**:

**Comment by snc** [comment] 2022-03-15 12:24
I can confirm this issue with the officially released iOS 15.4 version. Disabling antialias prevents this issue.

**Comment by sbesh91** [comment] 2022-03-16 00:48
Also experiencing this with an AlphaFilter between two graphics.  I do hope that we can have antialiasing back soon.

**Comment by cydalby** [comment] 2022-03-22 10:08
Also experiencing this bug, disabling antialiasing fixes

**Comment by tamaseszenyi** [comment] 2022-03-23 11:50
I can also confirm this. The issue can be reproduced on the official Pixi example site in ios 15.4. It's very annoying, we had to hotfix a recently released game because of this shit. We disabled the antialiasing but this cannot be a final solution.

**Comment by liorneo** [comment] 2022-03-31 06:15
i can confirm this is the case also in chrome IOS. disabling antialias fix the issue for now.

**Comment by cydalby** [comment] 2022-03-31 08:18
> i can confirm this is the case also in chrome IOS. disabling antialias fix the issue for now.

Chrome is just a skinned Safari on iOS, it doesn't run Chromium

**Comment by liorneo** [comment] 2022-03-31 08:28
> > i can confirm this is the case also in chrome IOS. disabling antialias fix the issue for now.
> 
> Chrome is just a skinned Safari on iOS, it doesn't run Chromium

thanks for helping.

**Comment by liorneo** [comment] 2022-03-31 08:40
looks like a webkit bug which has been fixed for next update, guess we have to live without antialias for now.. 
https://bugs.webkit.org/show_bug.cgi?id=238022
https://bugs.webkit.org/show_bug.cgi?id=238171

**Comment by furic** [comment] 2024-05-21 06:01
This is a quick fix for this issue but it would be nice to include this in pixi:

```
let isSafari154 = navigator.userAgent.includes('Safari') && navigator.userAgent.includes('Version/15.4');

pixiApplication = new PIXI.Application({
	antialias: !isSafari154,
	...
});
```

**Comment by GoodBoyDigital** [comment] 2024-11-09 20:18
closing as look like this webkit bug has been addressed!

**Closed by GoodBoyDigital** 2024-11-09 20:18 UTC
