### ISSUE TITLE
Blurry SVG loaded from URL (without any sprite scaling)

### ISSUE THREAD

**Issue by joakin** [pixijs/pixijs#6113] opened 2019-09-21 13:07 UTC
### Expected Behavior
Loading an SVG sprite and rendering it should be crisp on HiDPI displays (`window.devicePixelRatio == 2`)

<img width="495" alt="Screenshot 2019-09-21 at 14 59 38" src="https://user-images.githubusercontent.com/657839/65373643-75b17700-dc80-11e9-9e9e-f7cae7fe2494.png">

### Current Behavior

The SVG renders fuzzy:

<img width="481" alt="Screenshot 2019-09-21 at 14 58 54" src="https://user-images.githubusercontent.com/657839/65373633-603c4d00-dc80-11e9-9157-025aa2952999.png">

Example: https://codepen.io/joakin/pen/YzKdqJK?editors=0010

### Possible Solution

I'm not sure why it isn't rasterizing the image appropriate to devicePixelRatio so that it isn't blurry.

I've searched around and tried adding scale and overriding width and height on the loader options but they seem to have no effect. I've also tried to mess with resolution on PIXI.settings and many other things, but nothing had any effect.

It is possible I'm doing something wrong or I've missed something but I've been reading API docs and examples from the official site and couldn't figure it out.

### Steps to Reproduce

* See example here: https://codepen.io/joakin/pen/YzKdqJK?editors=0010

### Environment

- **`pixi.js` version**: PixiJS 5.1.3 - ✰ WebGL 2 ✰
- **Browser & Version**: Chrome 76
- **OS & Version**: OSX 10.14.6
- **Running Example**: https://codepen.io/joakin/pen/YzKdqJK?editors=0010
- **Expected example, plain Canvas 2d**: https://codepen.io/joakin/pen/OJLrNdR?editors=0010

**Comment by ivanpopelyshev** [comment] 2019-09-22 11:49
https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/textures/resources/SVGResource.js#L38

need to somehow set that `scale` options, but I dont see that loader actually passes options to texture resource: 

https://github.com/pixijs/pixi.js/blob/dev/packages/loaders/src/TextureLoader.js#L23

https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/textures/Texture.js#L401

Now you have two alternatives: 

1. Wait for one of our SVG guys to tell how they deal with that stuff in v5, or wait when someone adds an option to pass options to loader.
2. Try something yourself based on the info i gave you.

**Comment by joakin** [comment] 2019-12-21 13:59
Still a bug, don’t close it bot

**Comment by aaclayton** [comment] 2020-12-15 14:29
This is still not working well. Please reopen.

**Comment by Feu-Secret** [comment] 2020-12-15 16:12
Is this linked to this?
getResolutionOfUrl is called in Texture.fromLoader without default resolution value.
```
import { settings } from '../settings';

/**
 * get the resolution / device pixel ratio of an asset by looking for the prefix
 * used by spritesheets and image urls
 *
 * @memberof PIXI.utils
 * @function getResolutionOfUrl
 * @param {string} url - the image path
 * @param {number} [defaultValue=1] - the defaultValue if no filename prefix is set.
 * @return {number} resolution / device pixel ratio of an asset
 */
export function getResolutionOfUrl(url: string, defaultValue?: number): number
{
    const resolution = settings.RETINA_PREFIX.exec(url);

    if (resolution)
    {
        return parseFloat(resolution[1]);
    }

    return defaultValue !== undefined ? defaultValue : 1;
}
```

**Comment by Levix** [comment] 2020-12-16 02:32
I had the same problem.

**Comment by devedse** [comment] 2021-03-07 17:22
I'm also running into this issue. As you can see the black --> green line isn't quite sharp:

![image](https://user-images.githubusercontent.com/2350015/110248525-eed68400-7f71-11eb-8c16-26d96ab1e9a4.png)

I've tried loading the image as follows:
```
    var locktestsvg = "images/locktest.svg";
    let locktesttexture = await PIXI.Texture.fromURL(locktestsvg, {resourceOptions: {scale:20}});
    var locktest = new PIXI.Sprite(locktesttexture)
```

But it seems the scale: 20 isn't doing anything.

**Comment by devedse** [comment] 2021-03-07 18:17
I managed to fix this using the following line of code:

```
let locktesttexture = await PIXI.Texture.fromURL(locktestsvg, {resolution: 10});
```

**Comment by derTobsch** [comment] 2021-03-08 13:08
>  {resolution: 10}

Hey @devedse, which version do you use? This does not work for me :)

**Comment by devedse** [comment] 2021-03-08 14:25
I use these NPM packages:
```
    "pixi-viewport": "^4.21.1",
    "pixi.js": "^6.0.0",
```

**Comment by joakin** [comment] 2021-06-12 06:35
Still a bug, don’t close it bot

**Comment by bigtimebuddy** [comment] 2021-06-14 18:16
This is not a bug. There's a mismatch with the resolutions causing your SVG image to render blurry. 

In the original example, the resolution of the Renderer/Application was set to `devicePixelRatio`, but the default resolution for SVG images is 1. This means that an SVG loaded with Loader is rendered at a _smaller_ resolution. Version 6.0.0 introduced (#7183) the ability to pass resolution and other properties to the loader to give you more control over how the loader rasterizes the SVG. Here's an example:

https://jsfiddle.net/bigtimebuddy/cftksqw6/

```js
app.loader.add("name", "path/to/my.svg", { metadata: {
  resolution: 2, // the native resolution of the texture, probably devicePixelRatio
  resourceOptions: {
    scale: 2 // should probably match devicePixelRatio too if the SVG's size is at @1x
  }
}})
```

The ability to control the rasterization of SVGs is a general feature because larger resolutions occupy much more memory (please don't set your scale to `20`!!). Understanding the user intent in these cases is difficult because Pixi doesn't know how big an SVG _needs_ to be, only the user does. 

Hope that helps clarify.

**Comment by ShukantPal** [comment] 2021-09-19 14:44
I think we can close this, feel free to reopen if there are any more questions.

**Closed by ShukantPal** 2021-09-19 14:44 UTC
Labels: 👍 Not A Bug

**Comment by FalcoG** [comment] 2024-05-04 21:19
Since this is still something that has to be done by the user and as this is the only place where I could find any information about it, I'd like to give an updated example for pixi v7.

```javascript
import { Assets } from 'pixi.js'

const optionsHiDPI = {
  // https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio#value
  resolution: window.devicePixelRatio,
  resourceOptions: {
    scale: window.devicePixelRatio
  }
}

const myCustomVector = await Assets.load(
  { src: "path/to/vector.svg", data: optionsHiDPI }
);
```
and to use it with the `<Sprite />` component from pixi-react, replace the prop "image" with "texture";
```
<Sprite
  texture={myCustomVector}
  ...
/>
