### ISSUE TITLE
Bug: huge performance penalty with pointermove with very large Containers

### ISSUE THREAD

**Issue by joergplewe** [pixijs/pixijs#9156] opened 2023-02-12 11:13 UTC
### Current Behavior

Even in non-interactive scenes with large numbers of elements (>>10000) in a `ParticleContainer`, just moving the mouse above the canvas leads to a FPS-drop of >30%.

Profiler shows that Pixi spends a lot of time in the event system, esp. `notifyTarget`:

<img width="856" alt="image" src="https://user-images.githubusercontent.com/3304539/218307132-0e9c54dc-dbde-48a7-88ff-eace4e12a2a5.png">

I tried to set `interactive = false; interactiveChildren = false; hitArea = { contains: () => false }` wherever I could without effect.

Mouse wheel in contrast is for free (also seen in profiler).

I suspect that the same holds for `Container` instead of `ParticleContainer`, but I haven't investigated that.

### Expected Behavior

No performance penalty.
As it was in Pixi6.

### Steps to Reproduce

As an example, use Pixi's `ParticleContainer` example: https://pixijs.io/examples/#/demos-basic/particle-container.js

Push the number child elements to the edge where performance gets critical but still is around 60FPS (30000 on my business notebook). Then just moving mouse above the canvas gives a >30% performance drop.

### Environment

- **`pixi.js` version**: 7.1.2
- **Browser & Version**: any
- **OS & Version**: any
- **Running Example**: https://pixijs.io/examples/#/demos-basic/particle-container.js

**Comment by bigtimebuddy** [comment] 2023-02-13 14:15
@Zyie can you look at this?

**Comment by joergplewe** [comment] 2023-02-13 15:20
aehm ... `interactive` and `interactiveChildren` are `boolean`?

```
export interface FederatedEventTarget extends utils.EventEmitter, EventTarget {
...
    /** Whether this event target should fire UI events. */
    interactive: boolean;
    /** Whether this event target has any children that need UI events. This can be used optimize event propagation. */
    interactiveChildren: boolean;
...
```

**Comment by SuperSodaSea** [comment] 2023-02-13 15:25
> aehm ... `interactive` and `interactiveChildren` are `boolean`?

We have changed this in the latest development version (see #9089, will be in 7.2.0):

<https://github.com/pixijs/pixijs/blob/6a3b1e86c819b60231a5c4fb04b8d447461a7f86/packages/events/src/FederatedEventTarget.ts#L75-L76>

**Comment by bigtimebuddy** [comment] 2023-02-13 16:02
Yeah, sorry for not giving that explanation @joergplewe. We added new interactive types to help with performance tuning.

This indeed seems like a problem. The current release v7 release is going to have issues with large containers, which is why we are trying to address in v7.2.0. I would expect my example to do a better job at ignoring those children and I'm not sure why it's not.

**Comment by Zyie** [comment] 2023-02-14 16:14
@bigtimebuddy I haven't had time to fully dig into this but it seems like this is an issue with `globalpointermove`

It seems to fire even if `interactive = 'none'`

**Closed** 2023-02-15 17:56 UTC
Labels: 🕷 Bug, 🔥 High Priority

**Comment by TobiasWehrum** [comment] 2023-03-04 00:21
Does the pull request solve the performance problem behind this, or just the

> I tried to set `interactive = false; interactiveChildren = false; hitArea = { contains: () => false }` wherever I could without effect.

?

I'm currently trying to migrate a codebase from v6 to v7, and I saw would looks like the same performance drop described in the opening post when the mouse is moved. Since a few of the children in my big container actually want to receive pointer events I cannot just set `interactiveChildren = false;`. Updating to v7.2.0-rc which has the pull request above still shows the same performance drop for me.

**Comment by rwampler** [comment] 2023-03-04 00:44
I also saw same issue during my migration from v6, and 7.2.0 does seem to improve quite a bit, but not completely with performance still seemingly tied to number of sprites. This starts to become noticeable with more than 1-2k sprites, even when sprites hidden (but still in container)

In my case, I'm also only using pointer-click events, so ideally I wouldn't experience any overhead when moving mouse/pointer around, which seems unexpected when unneeded

**Comment by TobiasWehrum** [comment] 2023-03-04 00:57
> even when sprites hidden (but still in container)

Ha, I just came back here to add that to my post. My app is (among other things) a level editor which has a ton of sprites, but most of them with `visible = false` because they are currently outside the bounds of the screen. Since there aren't even that many visible, I suspected that hidden sprites are still processed - and true enough, even if *all* of them are invisible, the performance drop stays the same.

I wonder if that's the difference between v6 (where everything was fine even for the biggest game maps) and v7.

**Comment by joergplewe** [comment] 2023-03-04 10:09
All I can say is that my issue is fully solved since 7.2.0-beta.

**Comment by bigtimebuddy** [comment] 2023-03-04 11:41
If there are performance regressions with events different from this original post, please file a new issue with an example.

**Comment by xpluscal** [comment] 2024-06-18 13:03
A similar issue seems to reoccur with version 8 - pointermove events taking up 30-50% of scripting time, even if no on pointermove listeners are set. Whats the best way to solve it here? Make non interactive is a challenge because on pointerdown events wouldn't fire right?
