### ISSUE TITLE
Error - no dependency version info found

### ISSUE THREAD

**Issue by chrishare10** [pixijs/pixijs#8822] opened 2022-11-04 15:23 UTC
Received this error over the past few days:

> [Package Error] "@pixi/core" no dependency version info found. (Imported by "@pixi/filter-alpha").
> 
> The package "@pixi/filter-alpha" depends on "@pixi/core" as a dependency,
> but did not list any dependency version info in its package manifest.
> Without this information, the CDN is unable to properly resolve this import.
> 
> How to fix:
> - Let the "@pixi/filter-alpha" package author know that "@pixi/core" needs to be included in their package.json manifest.
>  - Use https://skypack.dev/ to find a web-friendly alternative to find another package.
> 
> 
> throw new Error("[Package Error] \"@pixi/core\" no dependency version info found. (Imported by \"@pixi/filter-alpha\").");
> export default null;

Here are my current imports in case you need them:

> import * as PIXI from 'https://cdn.skypack.dev/pixi.js';
> import { KawaseBlurFilter } from 'https://cdn.skypack.dev/@pixi/filter-kawase-blur';
> import { NoiseFilter } from 'https://cdn.skypack.dev/@pixi/filter-noise';

**Comment by SuperSodaSea** [comment] 2022-11-04 15:33
@bigtimebuddy Seems that the `pixiDependency` in v7 is not compatible with [skypack.dev](https://skypack.dev/)?

**Comment by bigtimebuddy** [comment] 2022-11-04 15:34
Closing, as this is a duplicate of #8798, however, a different tool.

**Closed by bigtimebuddy** 2022-11-04 15:34 UTC
