### ISSUE TITLE
Bug: pixi application's stage can not add child Sprite instance in 7.3.x version

### ISSUE THREAD

**Issue by coderavel** [pixijs/pixijs#10065] opened 2024-01-05 06:46 UTC
### Current Behavior

hi

first, i can not use english well, sorry

i found issue about addChild() of stage of pixi application, in version 7.3.2 and 7.3.3

look at image below,

![image](https://github.com/pixijs/pixijs/assets/31347201/969fd0f7-45ab-4e8b-b556-be8b1d99d5f4)

but this bug was not shown in version 7.2.4

So, to solve this problem, I copied the entire npm_modules/@pixi folder from the 7.2.4 version to the 7.3.3 version.

As a result, I was able to solve this problem.

### Expected Behavior

expect no error

### Steps to Reproduce

1. using 'npx create-react-app [project name] --template=typescript'
2. npm install pixi.js
3. make component and coding like below

```tsx
import React, { FC, useEffect, useRef } from 'react';
import * as PIXI from 'pixi.js'

interface MixiProps {
  readonly width: number,
  readonly height: number,
}

const Mixi: FC<MixiProps> = (props: MixiProps) => {

  const canvasRef = useRef<HTMLDivElement>(null);

  useEffect(() => {

    const pixiApp = new PIXI.Application<HTMLCanvasElement>({
      width: props.width,
      height: props.height,
      background: 'black'
    });

    const testSprite = PIXI.Sprite.from('/images/1.png');

    pixiApp.stage.addChild(testSprite);  // <<<<<<<<<<<<<<------------ error point
    
    canvasRef.current?.appendChild(pixiApp.view);

    pixiApp.start();

    return () => {
      pixiApp.stop();
    }

  }, [])
  
  return (
    <div ref={canvasRef}></div>
  )
};

export default Mixi;
```

4. npm start 

### Environment

- **`pixi.js` version**: *e.g. 7.3.3*
- **Browser & Version**: *e.g. Chrome latest*
- **OS & Version**: *window 10,*
- **Running Example**:  can not
- **editor and framework**: visual studio code / react 18 (using create-react-app)

### Possible Solution

copy from all files in  7.2.4's @pixi folder to 7.3.3's (just to solve this problem, but maybe some new error will be raised)

**Comment by SuperSodaSea** [comment] 2024-01-08 10:45
This seems to be a duplicate of #9747. [PixiJS 7.3.0+](https://github.com/pixijs/pixijs/releases/tag/v7.3.0) requires Typescript 5, but `create-react-app` creates your app with Typescript 4 by default, so you just need to run `npm install typescript@5` to get rid of this annoying error.

**Comment by bigtimebuddy** [comment] 2024-01-08 16:07
I'm closing this as a duplicate of #9747

**Closed** 2024-01-08 16:07 UTC
Labels: 👍 Not A Bug
